// MODULE V — RITUAL & CEREMONY: QUIZ BANK
window.MODULE_5_QUIZZES = {
  lessons: {
    r1: {
    title: 'Lesson 1 — What Ritual Actually Is',
    passThreshold: 0.8,
    questions: [
      { type:'mc', q:'In the Yoruba framework, ritual is best understood as:',
        choices:['Magic that compels supernatural results','A structured embodied language addressed to multiple audiences','Symbolic theater with no real effect','A private psychological technique'],
        answer:1, rationale:'Ritual is communication — to spirit, community, and self — not coercive magic.' },
      { type:'mc', q:'The three audiences of every ritual are:',
        choices:['Self, family, government','Spirit world, community, self (body)','Past, present, future','Eshu, Orunmila, ancestors'],
        answer:1, rationale:'Spirit world, living community, and the practitioner\'s own body — all three must be addressed.' },
      { type:'tf', q:'A ritual that addresses only one audience (e.g. private journaling) is fully complete.',
        answer:false, rationale:'Complete ritual addresses all three audiences; single-audience work is partial.' },
      { type:'mc', q:'The four-part anatomy of an ebọ is:',
        choices:['Setup, action, prayer, cleanup','Intention, threshold, gift, dispatch','Cleanse, invoke, sacrifice, leave','Open, sing, dance, close'],
        answer:1, rationale:'Intention names the rite; threshold opens the channel; gift is the offering proper; dispatch closes cleanly.' },
      { type:'fill', q:'The Yoruba word for "offering" — the basic unit of ritual — is ___.',
        answer:'ebo', accept:['ebọ','ebo'], rationale:'Ebọ ranges from a few drops of water to elaborate ceremonies.' },
      { type:'mc', q:'Why does African ritual emphasize embodied movement (kneeling, drumming, dance)?',
        choices:['It looks more impressive','The spirit world hears the body more clearly than the mind','Western tradition requires it','It burns calories'],
        answer:1, rationale:'The body is the primary instrument; mental-only ritual misses the channel.' },
      { type:'tf', q:'"Sacred time" in ritual means the rite creates its own temporal containment, distinct from clock time.',
        answer:true, rationale:'The fold of sacred time opens with the threshold and closes at dispatch.' }
    ]
  },
  r2: {
    title: 'Lesson 2 — The Daily and the Seasonal',
    passThreshold: 0.8,
    questions: [
      { type:'mc', q:'The four tiers of traditional rhythm are:',
        choices:['Hourly, daily, weekly, monthly','Daily, weekly, monthly, seasonal','Morning, noon, evening, night','Personal, family, community, national'],
        answer:1, rationale:'Each tier nests the next; daily is the constant pulse, seasonal is the annual shape.' },
      { type:'mc', q:'A well-calibrated daily practice should be approximately:',
        choices:['1-2 hours','30-60 minutes','3-7 minutes','As long as you can manage'],
        answer:2, rationale:'Small enough to do every day, even on hard days. Consistency beats elaborateness.' },
      { type:'tf', q:'When you miss a day of practice, the ancestors keep score and require apology.',
        answer:false, rationale:'The ancestors do not punish lapses. The discipline is in returning, not in never-leaving.' },
      { type:'fill', q:'In the traditional Yoruba weekly correspondences, ___ is associated with Friday.',
        answer:'oshun', accept:['oshun','ọṣun','osun'], rationale:'Friday — Oshun: beauty, art, love, abundance.' },
      { type:'mc', q:'Sunday in diaspora practice is most commonly devoted to:',
        choices:['Eshu','Shango','Ancestor work and the household\'s spiritual axis','Public ceremony only'],
        answer:2, rationale:'Sunday — long altar time, weekly reflection, ancestor focus.' },
      { type:'mc', q:'A monthly ancestor evening should generally take:',
        choices:['10-15 minutes','30-60 minutes','2-3 hours','A full weekend'],
        answer:2, rationale:'An evening cleared of other plans — long enough for a fuller meal and longer reflection.' }
    ]
  },
  r3: {
    title: 'Lesson 3 — The Threshold Rites',
    passThreshold: 0.8,
    questions: [
      { type:'mc', q:'The Yoruba naming ceremony is called:',
        choices:['Egungun','Ìkómojáde','Ifa','Bembé'],
        answer:1, rationale:'Ìkómojáde — "bringing the child out" — held on day 7, 8, or 9 after birth.' },
      { type:'mc', q:'A traditional Yoruba child receives:',
        choices:['A single given name','One name plus surname','Multiple names — oríkì, day-name, circumstance, lineage','A nickname only'],
        answer:2, rationale:'The child leaves with a library of names, each calling forth a quality of destiny.' },
      { type:'tf', q:'A coming-of-age rite missed in adolescence cannot be recovered later in life.',
        answer:false, rationale:'A rite postponed is not a rite forfeited. The soul has been waiting.' },
      { type:'mc', q:'The five elements of a recovered late coming-of-age rite are:',
        choices:['Fast, reckoning, teaching, mark, witness','Pray, fast, study, celebrate, rest','Buy gifts, eat, drink, dance, sleep','Ritual bath only'],
        answer:0, rationale:'Fast (separation), reckoning (trial), teaching (instruction), mark (body record), witness (community).' },
      { type:'mc', q:'Traditional Yoruba marriage is fundamentally:',
        choices:['A contract between two individuals','A joining of two lineages with both sets of ancestors','A purely religious sacrament','A government registration'],
        answer:1, rationale:'Two ancestral lines become one extended family — both lineages, both communities present.' },
      { type:'fill', q:'In Yoruba marriage, the symbolic gifts exchanged between families — kola, salt, honey, palm wine — are part of the ___.',
        answer:'idana', accept:['ìdána','idana','bride-price'], rationale:'Ìdána — the symbolic gift exchange, mutual rather than commercial.' },
      { type:'tf', q:'You can perform additional funeral rites for someone who died years ago.',
        answer:true, rationale:'The dead have no expiration date for receiving rites. They are patient.' }
    ]
  },
  r4: {
    title: 'Lesson 4 — The Body in Ceremony',
    passThreshold: 0.8,
    questions: [
      { type:'mc', q:'In the Yoruba house, the bata drums are particularly associated with:',
        choices:['Eshu','Yemoja','Shango','Obatala'],
        answer:2, rationale:'When the bata speak, Shango is being summoned; the rhythm is his voice.' },
      { type:'mc', q:'Why does kneeling matter in African ceremony?',
        choices:['To show inferiority','To position the body for receiving','To save space','It is just tradition'],
        answer:1, rationale:'You kneel because you are arriving at a moment too large to receive standing.' },
      { type:'fill', q:'The orisha colors are: white = Obatala, red/white = Shango, yellow/gold = Oshun, blue/white = ___.',
        answer:'yemoja', accept:['yemoja','yemaya','yemonja'], rationale:'Yemoja — the great mother of waters, blue and white.' },
      { type:'tf', q:'African ceremonial dance is primarily aesthetic display and entertainment.',
        answer:false, rationale:'It is prayer performed by the entire body — specific patterns address specific orisha.' },
      { type:'mc', q:'The shared ceremonial meal at the end of a rite functions to:',
        choices:['Feed the body, re-knit community, ground the spiritual','Demonstrate wealth','Reward the priest','Replace the prayer'],
        answer:0, rationale:'All three functions — and grounding the spiritual in actual livable life.' },
      { type:'mc', q:'Smoke (incense, sage, palo santo) in ritual primarily:',
        choices:['Freshens the air','Cleanses the space and carries prayer upward','Drives away insects','Has no real function'],
        answer:1, rationale:'The rising smoke is prayer ascending; cleared air signals the channel is open.' }
    ]
  },
  r5: {
    title: 'Lesson 5 — Building a Year of Ritual',
    passThreshold: 0.8,
    questions: [
      { type:'mc', q:'The four solar markers used as the simplest annual frame are:',
        choices:['Four orisha feast days','Spring equinox, summer solstice, autumn equinox, winter solstice','New Year, Easter, July 4, Christmas','Four moon phases'],
        answer:1, rationale:'These universally-recognizable dates carry an Africana practice cleanly.' },
      { type:'mc', q:'The autumn equinox rite is thematically focused on:',
        choices:['New beginnings','Peak celebration','Harvest, ancestor honor, taking stock','Release and the long night'],
        answer:2, rationale:'Autumn — gathering in, the fuller ancestor evening, the harvest meal.' },
      { type:'mc', q:'The four tiers of practice can be thought of as:',
        choices:['Beginner, intermediate, advanced, expert','Seconds, minutes, hours, calendar of nested timepieces','Personal, family, community, public','Required, recommended, optional, bonus'],
        answer:1, rationale:'Daily=second hand, weekly=minute hand, monthly=hour hand, seasonal=calendar.' },
      { type:'tf', q:'In the African house, a separate sacred building is required to perform real ceremony.',
        answer:false, rationale:'The home is the primary temple. Attention turns the house into one.' },
      { type:'fill', q:'The orisha greeted at the household threshold is ___.',
        answer:'eshu', accept:['eshu','eṣu','esu','elegua','elegguá'], rationale:'Eshu — gatekeeper of the home — receives the threshold offering.' },
      { type:'mc', q:'The eventual move to community is described as:',
        choices:['Optional luxury','A structural necessity for serious practice — the great rites need elders and witnesses','Only for those who want to become priests','Required immediately'],
        answer:1, rationale:'Home practice can sustain years; the great ceremonies require community and trained elders.' }
    ]
  }
  },
  exam: {
    title: 'Module V Final Exam — Ritual & Ceremony',
    passThreshold: 0.8,
    questions: [
      { type:'mc', q:'Ritual in the African house is:',
        choices:['Magic','Structured embodied language to spirit/community/self','Symbolic theater','Private therapy'],
        answer:1, rationale:'Communication, not coercion.' },
      { type:'mc', q:'The four parts of an ebọ:',
        choices:['Setup/action/prayer/cleanup','Intention/threshold/gift/dispatch','Cleanse/invoke/sacrifice/leave','Open/sing/dance/close'],
        answer:1, rationale:'Anatomy of the offering.' },
      { type:'mc', q:'The four tiers of rhythm:',
        choices:['Hourly/daily/weekly/monthly','Daily/weekly/monthly/seasonal','Morning/noon/evening/night','Personal/family/community/national'],
        answer:1, rationale:'Nested timescales.' },
      { type:'fill', q:'The Yoruba naming ceremony is called ___.',
        answer:'ikomojade', accept:['ìkómojáde','ikomojade'], rationale:'"Bringing the child out."' },
      { type:'tf', q:'A missed coming-of-age rite can be recovered late in life.',
        answer:true, rationale:'The soul has been waiting.' },
      { type:'mc', q:'The five elements of a late coming-of-age rite:',
        choices:['Fast/reckoning/teaching/mark/witness','Pray/fast/study/celebrate/rest','Buy/eat/drink/dance/sleep','Bath only'],
        answer:0, rationale:'Each element is essential.' },
      { type:'mc', q:'The bata drums are the voice of:',
        choices:['Eshu','Yemoja','Shango','Obatala'],
        answer:2, rationale:'Drum and orisha bound together.' },
      { type:'fill', q:'Friday in the weekly correspondences is associated with ___.',
        answer:'oshun', accept:['oshun','ọṣun','osun'], rationale:'Beauty, abundance, love.' },
      { type:'mc', q:'Yoruba marriage joins:',
        choices:['Two individuals only','Two lineages with both sets of ancestors','Two religious sects','Two governments'],
        answer:1, rationale:'Lineage is fundamental.' },
      { type:'tf', q:'The home becomes a temple through architecture, not attention.',
        answer:false, rationale:'Attention is what consecrates the household.' },
      { type:'mc', q:'The autumn equinox rite focuses on:',
        choices:['New beginnings','Peak celebration','Harvest and ancestor honor','Release and long night'],
        answer:2, rationale:'Gathering in.' },
      { type:'mc', q:'When you miss a day of daily practice:',
        choices:['The ancestors punish you','You return without drama; the relationship resumes','You must redo a week','You start over'],
        answer:1, rationale:'Discipline is in the returning.' }
    ]
  }
};
