// ══════════════════════════════════════════════════════════════
// MODULE IV — DIVINATION: LISTENING TO THE BONES
//   Five lessons, ~8 pages each, essay-form voice.
//   Curriculum threads:
//     • Orunmila — orisha of wisdom, witness to creation, master of language
//     • The 16 Odu Ifa — the cosmic alphabet (256 combinations)
//     • Opele (divining chain), Ikin (palm nuts), Obi (kola/coconut)
//     • Dilogún (16 cowries) — the diaspora's adaptation
//     • Ethics of the diviner — the question of "should I tell"
//     • Everyday omens — divination before divination
// ══════════════════════════════════════════════════════════════
window.MODULE_4_LESSONS = [

  // ─── LESSON 1 — Why We Cast ─────────────────────────────────
  { id:'d1', name:'Why We Cast', time:'20 min',
    glyph:'◉', x:'50%', y:'30%',
    prompt:'What question have you been afraid to ask plainly?',
    lead:'Divination is not fortune-telling. It is the disciplined practice of asking a clear question and listening to a non-human answer.',
    excerpt:'Before we touch any tool — before any cowrie is cast or palm nut counted — we have to settle what divination actually is. It is not <em>predicting the future</em>. It is not magic tricks. It is <strong>structured listening</strong>: the ancient practice of asking a precise question of the universe and receiving an answer through a system the diviner does not control. The Yoruba have practiced it, refined it, and codified it for at least a thousand years. The system has held up.',
    pages: [
      `<p class="dropcap no-indent">There is a moment that comes for every serious student of African spirituality, usually around the third or fourth month of practice, when an unfamiliar pressure begins to rise in the chest. <strong>The questions are getting bigger.</strong> The journal entries are no longer "should I take this job" — they are "what am I actually here to do?" The altar candles are no longer placeholders for vague intention; they are illuminating real, specific dilemmas. And the tradition the elders have left for moments exactly like this is not <em>more thinking</em>. It is <em>divination</em>.</p>
       <p>Divination, in the African house, is not the cheap parody it has become in Western popular imagination — the carnival fortune-teller in the silk turban, the website that emails you a "daily prediction." Real divination is closer to what a brilliant elder does when they sit with you for an hour and, by the end, you understand your own life better than you did before. <em>The difference is that, in divination, the elder is the universe itself, speaking through a system of patterns the diviner has spent decades learning to read.</em></p>
       <div class="bk-quote">"Divination is not fortune-telling. It is structured listening to a non-human voice."</div>`,

      `<h3>What the System Actually Is</h3>
       <p class="no-indent">Imagine that the universe is constantly speaking — through events, dreams, coincidences, the way the wind moves, the order in which thoughts arrive in your mind. <strong>Most of us have lost the ability to hear it</strong>, or we never learned. Divination is a tool that converts the universe's continuous, ambient speech into <em>discrete answers to specific questions</em>. It does this by introducing a structured randomness — the cast of cowries, the throw of palm nuts, the toss of the divining chain — and by reading the resulting pattern against an enormous body of accumulated wisdom.</p>
       <p>In Yoruba Ifa divination, the system has 256 master patterns called <strong>Odu</strong>. Each Odu is a "verse" of the universe — a chapter in the book of how reality works. When the diviner casts and a particular Odu comes up, they recite or recall the stories, proverbs, prescriptions, and warnings associated with that Odu, and they apply them to the question the client brought. <em>The randomness of the cast selects the page; the wisdom of the tradition reads it.</em></p>
       <p>This is why divination is not arbitrary. The randomness is genuine — neither the diviner nor the client can predict which Odu will come — but the <em>meaning</em> attached to each Odu has been refined by countless diviners over countless cases over many centuries. <strong>You are not consulting one person's intuition. You are consulting a thousand-year accumulation of pattern-recognition.</strong></p>`,

      `<h3>Why Africa Built This</h3>
       <p class="no-indent">Every traditional culture has divinatory systems — the I Ching in China, the runes in northern Europe, the Roman augurs reading bird flights, the Norse seers consulting the cup. African civilizations, and Yoruba civilization in particular, built one of the most <em>refined and philosophically coherent</em> systems on earth. There is a reason. Yoruba culture is, at its root, <strong>a culture organized around the question of destiny</strong>. We met Ori in Module I — the destiny-self chosen before birth, the contract you came in carrying. The whole of Yoruba spiritual life is oriented around <em>discerning what your Ori actually came to do</em> and aligning your everyday choices with that deeper script.</p>
       <p>Divination, in this context, is the <strong>practical instrument of Ori work</strong>. You cannot consult your Ori through ordinary thinking — the ordinary mind is too entangled in fear, social pressure, and habit to see clearly. You have to step outside ordinary thinking. <em>The cowries step you outside.</em> The palm nuts step you outside. The cast is a moment when something other than your daily anxiety gets a turn to speak. <strong>That is what divination is for.</strong></p>
       <div class="bk-quote">"You cannot consult your Ori through ordinary thinking. The cowries step you outside."</div>`,

      `<h3>What Divination Is Not</h3>
       <p class="no-indent">A few corrections, because the diaspora has been fed a lot of bad information. <strong>Divination does not predict the future.</strong> The future is not a fixed object to be read. The future is a probability cloud shaped by your current trajectory, your character, your unresolved patterns, and the choices ahead of you. What divination does is <em>read the present accurately</em> and <em>describe the future that is currently most likely if nothing changes</em>. If the reading shows trouble ahead and the trouble is something that needs to change, the reading also gives you the prescription — the offering, the ritual, the behavioral shift — that <strong>changes the trajectory and changes the future</strong>.</p>
       <p><strong>Divination is not a substitute for thinking.</strong> A good reading does not replace your decision-making. It <em>informs</em> it. The diviner does not tell you what to do; they show you what is currently in motion, and they show you what the elders' wisdom suggests for situations like this one. The decision remains yours. <em>You are not absolved by the cowries.</em></p>
       <p><strong>Divination is not entertainment.</strong> Do not consult the system about trivial matters. The Yoruba elders are clear: <em>Ifa speaks for those who come with weight</em>. You do not throw the chain to ask whether to wear the blue dress. You throw the chain when a major decision is on the table, when a hidden pattern needs to surface, when you need a perspective larger than your own. Trivializing the system is one of the fastest ways to lose your right to use it.</p>`,

      `<h3>Three Levels of Divination</h3>
       <p class="no-indent">The tradition distinguishes three levels of divinatory practice, increasing in formality and authority:</p>
       <p><strong>1. Everyday omens — the noticing.</strong> Available to everyone, requiring no tools. Reading the signs that arrive uninvited: the bird that flies into your window the day after you considered breaking the engagement. The dream three nights running. The stranger who says the exact thing your ancestor said. <em>The universe speaks constantly; the everyday diviner has trained themselves to notice.</em> We will return to this in lesson five.</p>
       <p><strong>2. Tool-based personal divination — the simple cast.</strong> Available to any practitioner who has been instructed: kola nut (obi), coconut, dilogún (16 cowries) for binary or simple numeric answers. Used by individuals to consult on their own lives, by family elders to read the household, by the early-stage student to develop the listening ear. This is the level we will spend most of this module on.</p>
       <p><strong>3. Ifa divination — the formal reading.</strong> Performed only by an initiated <em>Babalawo</em> (male) or <em>Iyanifa</em> (female). Uses the opele (divining chain) for routine readings or the ikin (16 sacred palm nuts) for the most weighty consultations. Requires years of memorizing the Odu corpus — hundreds of verses for each of the 256 patterns. This is not something the lay practitioner does. <em>This is something the lay practitioner consults.</em></p>`,

      `<h3>When to Cast — and When Not To</h3>
       <p class="no-indent">A teaching the elders return to: <strong>not every question deserves a cast</strong>. The system honors questions that are: (a) <em>genuine</em> — you actually do not know the answer; (b) <em>weighty</em> — the answer matters; (c) <em>answerable</em> — within the system's competence; and (d) <em>asked from a position of openness</em> — you are willing to receive an answer you did not expect.</p>
       <p>If you already know the answer and you are asking the cowries to confirm it — <strong>you are not divining; you are seeking permission</strong>. The cowries will sometimes give you the answer you wanted. Just as often, they will give you the answer you were avoiding. <em>If you are not ready to hear that, do not cast.</em></p>
       <p>If the question is petty (<em>which restaurant should we go to</em>), the cowries will often give you nonsense, because the system is calibrated for matters that affect destiny. If the question is unanswerable (<em>does my dead aunt forgive me</em>), the cowries can speak to it but the answer will be approximate; some questions are better brought to the ancestor altar directly.</p>
       <p>The right questions are: <em>What is the energy currently around this decision? What is being shown to me right now that I am missing? What does my Ori suggest about this path? Is the door open or closed for this venture? What offering would clear the obstacle in front of me?</em> These are the questions Ifa was built to answer.</p>`,

      `<h3>The Diviner's Posture</h3>
       <p class="no-indent">Whether you ever become a tool-using diviner or remain a careful reader of everyday omens, there is a posture you must develop, and the elders insist on it: <strong>you must become someone who can be told the truth</strong>. The system's gift to you is exactly proportional to your willingness to receive what it shows. If you flinch every time the answer is uncomfortable, the answers become harder to read — not because the system is punishing you, but because <em>your own resistance distorts the signal</em>.</p>
       <p>So, before any tool work, the inner work begins: <strong>can I sit with bad news?</strong> Can I receive a truth about my own behavior and actually let it land? Can I be told that the relationship I am defending is the relationship that is harming me, and not immediately argue with the messenger? <em>The cowries are mirrors. If you cannot stand to look at the mirror, you will throw the cowries against the wall and call them broken.</em></p>
       <p>The diviner's posture is humility, attention, and a deep willingness to be wrong about your own life. It is not naïve — the diviner cross-checks, asks follow-up questions, and refuses readings that feel forced. But it is fundamentally <em>open</em>. The student who develops this posture is already half a diviner before they ever touch a cowrie.</p>
       <div class="bk-quote">"The cowries are mirrors. If you cannot stand to look at the mirror, you will throw them against the wall and call them broken."</div>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">No tools yet. The work this week is preparation.</p>
       <p><strong>Practice 1 — Identify your real question.</strong> At your altar each evening, ask yourself: <em>What is the question I have been avoiding asking plainly?</em> Not the surface question (should I take the job). The deeper one (am I ready to grow up). Write it down. Refine it across the week. By Sunday, you should have a single, precise question that — if it could be answered honestly — would actually move your life.</p>
       <p><strong>Practice 2 — Notice resistance.</strong> When a friend, a book, a stranger, a dream offers you information about yourself this week, notice your first reaction. Was it openness or defense? Mark it. The diviner's training begins by <em>watching the flinch</em>.</p>
       <p><strong>Practice 3 — Pour libation, ask permission.</strong> Once during the week, at your ancestor altar, pour a small libation and speak: <em>"I am preparing to learn the listening practices of our people. Make me worthy. Open my ears. Show me what I have been missing."</em> Then sit for five minutes in silence. Note what surfaces.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#5a3a14;">Next chapter: <em>Orunmila — the Witness</em>, the orisha who saw it all happen and remembers.</p>`
    ]
  },

  // ─── LESSON 2 — Orunmila, The Witness ───────────────────────
  { id:'d2', name:'Orunmila — The Witness', time:'22 min',
    glyph:'◎', x:'25%', y:'52%',
    prompt:'Who, if anyone, has ever truly listened to the whole of you?',
    lead:'Orunmila was the only orisha at creation who paid attention. Now he is the orisha you consult when you need to be seen completely.',
    excerpt:'Before we touch any tool, we must meet the orisha behind it. <strong>Orunmila</strong> — also called Ifa — is the orisha of wisdom, language, divination, and witnessing. He was present at the creation of every soul; he watched each Ori choose its destiny; <em>he remembers what you came here to do, even when you have forgotten</em>. To consult divination is, finally, to ask Orunmila what he saw.',
    pages: [
      `<p class="dropcap no-indent">In the cosmology we laid out in Module I, every soul, before incarnating, knelt before Olódùmarè and received its <em>Ori</em> — the crown that holds the soul's destiny, the contract for this lifetime. The myth continues with a detail most students miss on first hearing: <strong>one orisha was watching when each soul made its choice</strong>. Not interfering, not advising — just <em>witnessing</em>. He stood at the threshold and observed every soul as it knelt, made its choice, and departed for the world. That witness was <strong>Orunmila</strong>.</p>
       <p>This is why, in the entire pantheon of orisha, only Orunmila has the specific authority to <em>tell you what you came to do</em>. He saw you choose. He saw the Ori you took. He remembers the contract you signed at the moment your finite mind has now mostly forgotten. <em>To consult divination is, in the deepest sense, to ask Orunmila to remind you of what you already know but cannot quite reach.</em></p>
       <div class="bk-quote">"Orunmila was watching when each soul chose its Ori. He remembers what you came here to do."</div>`,

      `<h3>The Orisha of Language Itself</h3>
       <p class="no-indent">Orunmila is also called <strong>Ifa</strong> — and "Ifa" in Yoruba refers both to the orisha and to the entire body of sacred wisdom (the 256 Odu, their verses, their stories, their proverbs, their prescriptions). The reason the name doubles is theological: <em>Orunmila is the orisha of language itself</em>. Specifically, he is the orisha of the <strong>structured language by which the universe describes itself to those who can read it</strong>.</p>
       <p>This is a subtle point but worth dwelling on. Most orisha have a domain — Ogun has iron, Yemoja has the ocean, Shango has lightning. Orunmila's "domain" is <strong>the underlying structure of meaning</strong>. He is the orisha whose territory is the patterns themselves — the way reality is composed of repeating themes, the way every situation a human can encounter has been encountered before in some form, the way wisdom accumulates and can be transmitted. <em>He is the librarian of the cosmos.</em></p>
       <p>This is also why Orunmila is sometimes called <strong>Eleri Ipin</strong> — "the witness of destiny" — and <strong>Igbakeji Olodumare</strong> — "second to Olódùmarè." Among the orisha, he sits closest to the Source, because his particular function is to translate what Olódùmarè knows into language a human can hear.</p>`,

      `<h3>His Color, His Day, His Symbols</h3>
       <p class="no-indent">Orunmila's <strong>colors</strong> are yellow and green — yellow for wisdom and the sun of clarity, green for the palm nuts and the iroko trees from which the sacred tools are made. His <strong>number</strong> is 16 (the count of the major Odu and the count of the sacred palm nuts). His <strong>day</strong> is <em>Ọjọ́ Awo</em> — "the day of the diviner" — which falls every fifth day in the traditional Yoruba four-day week (so once every Yoruba market cycle).</p>
       <p>His <strong>symbols</strong>: the <em>opele</em> (the divining chain — eight half-shells strung in two arms of four, used for routine readings); the <em>ikin</em> (16 sacred palm nuts, used for the most serious readings); the <em>opon Ifa</em> (the divining tray, carved with the face of Eshu watching from one edge — even Orunmila must let Eshu witness every cast); and the <em>iroke</em> (the divining tapper, a tall ivory or wooden wand used to call Orunmila's attention before a reading).</p>
       <p>His <strong>offerings</strong>: kola nuts (obi), coconut (obi alaba), palm wine, white yam, fish, hen — and, most importantly, <em>silence</em>. Orunmila is fed less by elaborate ritual than by the diviner's willingness to <strong>listen long</strong>. He is the orisha for whom impatience is a kind of insult.</p>`,

      `<h3>The Babalawo and Iyanifa</h3>
       <p class="no-indent">A person formally initiated into the priesthood of Orunmila is called <strong>Babalawo</strong> ("father of the secrets") if male, <strong>Iyanifa</strong> ("mother of Ifa") if female. (The historical record is mixed on women's initiation; in the strictest traditional houses it has been male-only, but reform houses across the diaspora have restored full ordination for women, and the elders we draw from in this curriculum recognize both.)</p>
       <p>The training is long. A traditional Babalawo's apprenticeship lasts <strong>seven years minimum</strong> — and that is the floor, not the ceiling. The apprentice must memorize verses for each of the 256 Odu. They must learn the protocols of the divining tray, the proper invocations, the ethics of consultation, and — crucially — the prescriptions: which offering, which ritual, which behavioral correction matches which Odu in which life-situation. <em>A fully trained Babalawo carries, in living memory, an oral library that would take many printed volumes to capture.</em></p>
       <p>This is why, in this module, we will not teach you Ifa divination proper. <strong>That is not honest to teach in a course.</strong> What we will teach you is the simpler tool-based divination that lay practitioners have always used (obi, dilogún), and we will teach you how to be a <em>good client</em> of a Babalawo when you eventually consult one. The full priestly path is a calling, and if it is yours, you will know.</p>`,

      `<h3>Orunmila in Personal Practice — Greeting</h3>
       <p class="no-indent">Even without initiation, you can begin a relationship with Orunmila. The protocol is similar to the relationships we built in Module III with the other orisha, but with one specific tone: <strong>patience</strong>. Orunmila is the slowest of the orisha to reveal himself. He does not give immediate signs. He does not visit you in dramatic dreams. He simply <em>begins to be present at the threshold of your thinking</em> — a quiet, dry, precise quality that arrives in your mind during the moments when you are about to make a foolish decision and something stops you.</p>
       <p>The greeting practice is simple. Once a week, ideally on a quiet evening, place a small dish at your altar with a single kola nut (or a small piece of coconut, if kola is not accessible — the elders accept the substitution in the diaspora). Light a yellow candle. Speak: <em>"Orunmila, witness of destiny, second to the Source — I greet you. I am beginning to learn to listen. Walk slowly with me. Show me what I came to do, when I am ready to see it."</em> Sit for five minutes. Then leave the offering for the night and dispose of it (return to earth) the next morning.</p>
       <p>Do this weekly for three months. By the third month, you will notice — not dramatic visions, but a <em>sharpening of judgment</em>. Decisions that were murky become clearer. Patterns you could not see become legible. <strong>That is Orunmila beginning to walk with you.</strong> He will not announce himself. He simply gets to work.</p>`,

      `<h3>Why Eshu Sits at the Edge of the Tray</h3>
       <p class="no-indent">A teaching that surprises students. Look at any traditional Ifa divining tray (<em>opon Ifa</em>) and you will see, carved at the top of the rim, the face of <strong>Eshu</strong>. Not Orunmila — Eshu. Why? Because even Orunmila must defer to the gatekeeper. Eshu opens or closes the channel by which the message travels. If Eshu is not greeted at the start of every reading, the reading will not flow correctly, no matter how skilled the diviner.</p>
       <p>Every Ifa session begins with a brief offering to Eshu — a tap on the corner of the tray with the iroke, a few words: <em>"Eshu, opener of the road, let the message reach. Let nothing distort the signal."</em> Only then does the diviner invoke Orunmila proper.</p>
       <p>The lesson here, even for the lay practitioner: <strong>greet Eshu first, always</strong>. We learned this in Module III. It applies to divination with absolute force. <em>Skip the greeting and the message will arrive scrambled, or not at all.</em></p>`,

      `<h3>The Two Modes — Routine and Weighty</h3>
       <p class="no-indent">In traditional practice, Ifa is consulted in two distinct modes:</p>
       <p><strong>Routine consultation</strong> — performed with the <em>opele</em> (divining chain). Used for most ordinary questions of life: should I travel, is this contract favorable, what is the energy around this household this month. The chain casts in seconds; the Odu reads quickly; the consultation is brief. A working Babalawo might do many such readings in a day.</p>
       <p><strong>Weighty consultation</strong> — performed with the <em>ikin</em> (16 sacred palm nuts). Used for major life questions: choosing a spouse, taking on a great undertaking, determining a child's destiny soon after birth, beginning a priestly path. The palm nut casting is laborious — it can take an hour or more for a single Odu to be determined — and the Babalawo will recite many verses, drawing out the full meaning. This is the mode for moments when you need <em>everything</em> the system can tell you.</p>
       <p>For your purposes — as a non-initiated student — the closest equivalent is: <em>simple obi (kola or coconut) divination for everyday questions; consult a trained Babalawo or Iyanifa for weighty matters.</em> We will teach you obi in lesson three. The weighty consultation is something you bring to a teacher, not something you self-administer.</p>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Three layered practices:</p>
       <p><strong>Begin the weekly greeting.</strong> Once this week, set up the small Orunmila offering described above (kola or coconut, yellow candle, five minutes of silence). Speak the greeting. Sit. Notice nothing dramatic; that is correct.</p>
       <p><strong>Read about your culture.</strong> Find one resource — book, recording, documented oral history — about Ifa or Yoruba divination, and spend at least 30 minutes with it this week. The point is not to become an expert. The point is to <em>show Orunmila that you are willing to study</em>. He notices.</p>
       <p><strong>Sit with the question from last week.</strong> The precise question you refined in lesson 1's homework — bring it to the altar at the end of the week, after the greeting offering. Do not cast anything yet. Just hold the question in front of the candle and ask: <em>"Is this the right question?"</em> Listen for the inner yes-or-no. By the time we cast obi in lesson three, the question must be clean.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#5a3a14;">Next chapter: <em>Obi — The First Cast</em>, where you learn the simplest and most ancient divinatory practice in the African house.</p>`
    ]
  },

  // ─── LESSON 3 — Obi: The First Cast ─────────────────────────
  { id:'d3', name:'Obi — The First Cast', time:'24 min',
    glyph:'◐', x:'70%', y:'48%',
    prompt:'What is the cleanest yes-or-no question you can phrase right now?',
    lead:'Four pieces of kola or coconut. Five possible answers. The simplest divination tool, available to every household, used for ten thousand years.',
    excerpt:'<strong>Obi</strong> divination — using four pieces of kola nut, or four pieces of fresh coconut in the diaspora — is the entry point. Every household had access to it. Every elder knew how to read it. Today you learn the casting, the five basic answers, and — most importantly — the protocols of <em>cleanliness, question-framing, and follow-up</em> that separate a good obi cast from a meaningless one.',
    pages: [
      `<p class="dropcap no-indent">If you take only one practical skill from this entire course, this should be it: <strong>how to cast obi</strong>. It is the simplest, oldest, and most accessible form of divination in the African house. It does not require initiation. It does not require the seven-year apprenticeship of Ifa. It does not require expensive tools. It requires four pieces of fruit, a clean cloth, an attentive heart, and a precise question. And when you have learned to do it well, you will have an instrument that has guided African households across continents and centuries.</p>
       <p>Obi is what the elder used when a daughter came to her with a hard choice. It is what the village head used when a dispute had to be settled. It is what the diaspora kept alive in kitchens across the Caribbean and the American South when more elaborate Ifa apparatus could not survive the conditions of slavery. <em>The four pieces are humble. The system they encode is complete.</em></p>`,

      `<h3>The Four Pieces — Kola or Coconut</h3>
       <p class="no-indent">Traditional obi uses the <strong>kola nut</strong> (obì in Yoruba) — a hard, lobed nut native to West Africa whose four (sometimes five) natural sections, when separated and cast, give the binary readings that drive the system. In Nigeria, Ghana, and Sierra Leone, kola is still the standard, sold in markets and used daily for hospitality, prayer, and divination.</p>
       <p>In the diaspora, where kola is scarce and expensive, <strong>fresh coconut</strong> is the accepted substitute. The protocol: take a fresh coconut, remove the husk, and crack the nut into <em>four roughly equal pieces</em>. Each piece must have one <strong>convex side</strong> (the curved outer shell, dark) and one <strong>concave side</strong> (the inner white meat, light). When cast, each piece will land either dark-side-up or light-side-up — and the four-piece cast will give a binary pattern read against a fixed table of meanings.</p>
       <p>Whether kola or coconut, the principle is the same: <strong>four pieces, each binary, four cast simultaneously, yielding 5 possible patterns</strong> (4-up, 3-up/1-down, 2-up/2-down, 1-up/3-down, 0-up/4-down). Each pattern has a name and a meaning, refined over millennia.</p>`,

      `<h3>The Five Patterns — A Standard Reading</h3>
       <p class="no-indent">The patterns and their core meanings (this is the simplified diaspora form; traditional Yoruba practice is more elaborate but the spine is the same):</p>
       <p><strong>Alaafia — 4 light, 0 dark (all white-side-up).</strong> "Peace." A clear, full <em>yes</em>. The road is open. Whatever you asked about will go well. Proceed with confidence.</p>
       <p><strong>Etawa — 3 light, 1 dark.</strong> A conditional <em>yes</em>. The path is favorable, but there is a small obstacle or qualification. Often the diviner asks a follow-up question to clarify. <em>The most common cast in everyday consultation.</em></p>
       <p><strong>Eyeife — 2 light, 2 dark.</strong> Mixed. Often interpreted as a strong "ask again" or "the answer is more complex than yes-or-no." The cast is asking you to refine the question. In some readings this is also taken as a <em>direct, blunt yes</em> — the most common interpretation in many diaspora houses. <strong>Know your tradition.</strong></p>
       <p><strong>Okanran — 1 light, 3 dark.</strong> A conditional <em>no</em>. The path is currently blocked or unfavorable, but the obstacle may be resolvable. The diviner asks: what offering would clear it? What needs to be addressed first?</p>
       <p><strong>Oyeku — 0 light, 4 dark (all shell-side-up).</strong> A full <em>no</em>. The road is closed. Do not proceed in this direction. Often associated with serious warning — sometimes connected to ancestor or death-related caution. The cast is grave. <em>Do not argue with this one.</em></p>`,

      `<h3>The Protocol — Step by Step</h3>
       <p class="no-indent">Here is how a clean obi cast is performed:</p>
       <p><strong>1. Cleanse.</strong> Wash your hands. Cleanse the space — sage, sweetgrass, frankincense, or simply a moment of attention with the words <em>"this space is clean for the asking."</em> Have a clean white cloth ready as your casting surface.</p>
       <p><strong>2. Greet Eshu and Orunmila.</strong> Pour a small libation outside the door for Eshu (a few drops of any spirit, with the words you have learned). At the altar, light a yellow candle for Orunmila and speak: <em>"Orunmila, witness of destiny, I come to you with a clean question. Help me hear what you have to say."</em></p>
       <p><strong>3. Frame the question precisely.</strong> Yes-or-no, single subject, no compound clauses. Wrong: <em>"Should I take the job and move to the new city?"</em> Right: <em>"Is taking this job in alignment with my path right now?"</em> Or: <em>"Is moving to the new city favorable for me at this time?"</em> One question per cast. The clarity of the question determines the clarity of the answer.</p>
       <p><strong>4. Hold the four pieces in your dominant hand.</strong> Speak the question aloud, three times. Touch the four pieces to your forehead, your heart, and the earth (or floor). Then cast them — not aggressively, not theatrically — onto the white cloth.</p>
       <p><strong>5. Read the pattern.</strong> Count light-side-up. Match to the table. Read the meaning. Sit with it for a moment before reacting.</p>
       <p><strong>6. If unclear — cast again, but differently.</strong> If the answer is etawa or eyeife (conditional or mixed), refine the question and cast a follow-up. <em>Never cast the same exact question twice in a row hoping for a different answer.</em> That is how you tell the cowries you do not want the truth.</p>
       <p><strong>7. Close the session.</strong> Thank Orunmila. Thank Eshu. Wrap the four pieces in the cloth. They should be returned to earth — buried in your garden, a houseplant, or scattered respectfully outside — within the day. <em>The pieces have done sacred work; do not toss them in the trash.</em></p>`,

      `<h3>What Makes a Question Castable</h3>
       <p class="no-indent">Not every question is appropriate for obi. The system favors questions that are: <strong>binary</strong> (genuinely yes-or-no), <strong>actionable</strong> (the answer changes what you would do), <strong>specific</strong> (about one decision, one person, one circumstance), and <strong>weighty</strong> (it actually matters).</p>
       <p>Castable: <em>"Is this contract favorable to sign at this time?"</em> "Is the energy around this relationship currently aligned with my growth?" "Should I attend the funeral this weekend or stay home and grieve privately?" "Is there an ancestor who wants to be greeted right now?"</p>
       <p>Not castable: <em>"What is the meaning of life?"</em> (open-ended, not binary). <em>"Which restaurant tonight?"</em> (too small). <em>"Will I be rich?"</em> (vague, no time-frame, no actionable consequence). <em>"Is my husband cheating on me?"</em> (the cowries cannot reliably read another person's hidden behavior; this question belongs to therapy, communication, or — if necessary — a trained Babalawo with a more sophisticated tool than obi).</p>
       <p>If your question fails the test, <strong>refine it</strong>. Sometimes the most useful work happens in the refinement, before any cast is made. <em>The clean question is half the answer.</em></p>`,

      `<h3>Frequency — How Often to Cast</h3>
       <p class="no-indent">The elders are stricter about this than most diaspora students expect. <strong>Obi is not a daily practice.</strong> Casting too often dulls the system — your ear gets sloppy, your questions get lazy, and the answers stop carrying weight. The traditional rhythm is: <em>cast when you have a real question; otherwise, do not cast</em>.</p>
       <p>For most practitioners, this means obi sessions <strong>every few weeks at most, sometimes only a few times a year</strong>. The casting is reserved for moments of genuine decision, not for general curiosity. If you find yourself wanting to cast every day, that is not a sign of devotion — it is a sign that you are using the cowries to avoid the harder work of <em>thinking</em>, of <em>sitting with uncertainty</em>, of <em>letting your own discernment develop</em>.</p>
       <p>A useful test: <strong>before any cast, write down what you think the answer will be.</strong> If you are right more than half the time, you may be casting too often — your own intuition is already serving you, and the obi is just confirming. The system is most useful when you genuinely do not know.</p>`,

      `<h3>The Hard Answer — Receiving Oyeku</h3>
       <p class="no-indent">Sooner or later, you will cast and the four pieces will land all dark-side-up. <strong>Oyeku.</strong> The full no. And it will land on a question where you wanted yes.</p>
       <p>The temptation, in that moment, is to argue. To re-cast. To assume the cast was sloppy. To rationalize. <em>This is the moment that defines whether you are a serious student or a tourist.</em> The serious student receives the no. They sit with it. They ask the follow-up question — not "is this really a no?" but <em>"what is the obstacle, and what would clear it?"</em> They listen. They make the offering or behavioral correction the system suggests. They wait the appropriate time. And then, perhaps, they cast again, with the obstacle addressed.</p>
       <p>The Yoruba elders have a saying: <em>Ifa kò pe èké</em> — "Ifa does not lie." The system is not malicious; it is honest. When the answer is no, the no is in your interest, even when you cannot see how. <strong>The diviner who has learned to receive Oyeku without flinching is a diviner whose other readings will sharpen, because they have proven they can be told the truth.</strong></p>
       <div class="bk-quote">"Ifa kò pe èké — Ifa does not lie. The diviner who can receive Oyeku without flinching is a diviner whose ear keeps sharpening."</div>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Now we cast.</p>
       <p><strong>Acquire the materials.</strong> Either find kola nuts (West African groceries, online importers) or buy a fresh coconut. If coconut, crack it carefully into four pieces, each with light side and dark side. Have a small clean white cloth ready. Set up your candle and the small libation cup.</p>
       <p><strong>Bring the question.</strong> The precise question you have been refining for two weeks. Make sure it passes the castable test (binary, specific, weighty, actionable).</p>
       <p><strong>Cast once.</strong> Follow the protocol exactly. Greet Eshu. Greet Orunmila. State the question three times. Cast. Read the pattern. Sit with what came up for at least five minutes before responding.</p>
       <p><strong>Record the cast in your journal.</strong> The date. The exact question. The pattern that came up. Your initial reaction. The action (if any) the answer suggests. Then — and this is the critical step — <em>over the next month, watch what unfolds</em>. Was the answer accurate? Did the action you took (or did not take) align with how things played out? <strong>This is how you learn obi — by reading, casting, and then watching reality confirm or challenge what came up.</strong> Over time, your trust in the system grows, and your ear sharpens.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#5a3a14;">Next chapter: <em>The Sixteen Odu</em> — the cosmic alphabet that underlies all Ifa divination.</p>`
    ]
  },

  // ─── LESSON 4 — The Sixteen Odu ─────────────────────────────
  { id:'d4', name:'The Sixteen Odu', time:'22 min',
    glyph:'◇', x:'30%', y:'78%',
    prompt:'Which pattern of your life keeps repeating, and what is it trying to teach?',
    lead:'Sixteen patterns, paired into 256 combinations. The cosmic alphabet by which Yoruba thought has read reality for a thousand years.',
    excerpt:'You will not learn to read Ifa in this lesson — that takes a Babalawo seven years. But you can learn the <strong>shape</strong> of the system: the 16 major Odu, what each one names, how they pair into 256 combinations, and why this particular system has held up for over a millennium. Today is conceptual literacy. After this, when you eventually consult a Babalawo, you will understand what they are doing.',
    pages: [
      `<p class="dropcap no-indent">There are sixteen of them. Sixteen master patterns, each one a "letter" in the alphabet by which the universe spells its meanings. The Yoruba call them the <strong>Odu Ifa</strong>. Each Odu has a name. Each Odu has hundreds — sometimes thousands — of associated verses, stories, proverbs, taboos, and prescriptions, accumulated by diviners over many centuries. Each Odu describes a particular <em>kind</em> of life-situation, a particular <em>flavor</em> of energy, a particular <em>chapter</em> in the great book of how reality unfolds for humans.</p>
       <p>And the sixteen, when paired with each other, generate <strong>256 combinations</strong> — and the 256 combinations are the actual working alphabet of Ifa divination. Every cast of the chain or the palm nuts produces one of the 256. Every life-situation a person can encounter is, in the elders' teaching, <em>a localized expression of one of the 256</em>. The system is finite, but its descriptive range is vast — much like the way 26 letters can compose every English book ever written.</p>
       <div class="bk-quote">"Sixteen patterns. 256 combinations. The cosmic alphabet."</div>`,

      `<h3>Why Sixteen?</h3>
       <p class="no-indent">A natural question: why this number? The technical answer: each Odu is a column of <strong>four binary marks</strong>, each mark either single (one stroke) or double (two strokes). Four binary slots gives 2⁴ = 16 possible patterns. The diviner produces these patterns by casting the opele (whose eight half-shells fall in two arms of four, each shell open or closed) or by counting the palm nuts left in the hand after grasping (an odd or even count gives a single or double mark, repeated four times to build the column).</p>
       <p>The deeper answer: <strong>sixteen is the number the tradition discovered, by long experiment, to be sufficient to describe the modes of reality without becoming unwieldy</strong>. Eight is too few — the patterns blur. Thirty-two is too many — the diviner cannot hold them all in living memory while also recalling the verses. Sixteen, paired into 256, is the <em>resolution</em> the system found. It is also (and the elders enjoy noting this) suggestively close to the resolution modern computing settled on for character encodings — and to the count of distinguishable phonemes in many human languages. <em>The Yoruba elders had reasons.</em></p>`,

      `<h3>The Sixteen Major Odu — A Roll Call</h3>
       <p class="no-indent">Here are the sixteen, in their canonical traditional order. Names vary slightly across houses; we use the most widely-attested forms. Beside each is a single-phrase association — a pinhole into the Odu's vast meaning, not a definition. Real engagement with each Odu would take many lessons; this is simply the alphabet.</p>
       <p><strong>1. Ogbe</strong> — light, openness, the orderly path; the morning of every undertaking.<br>
       <strong>2. Oyeku</strong> — death, endings, ancestors; the closing-down that makes new beginnings possible.<br>
       <strong>3. Iwori</strong> — vision, prophecy, second sight; the seeing-into-the-distance.<br>
       <strong>4. Odi</strong> — the womb, enclosure, gestation; what is hidden until ready.<br>
       <strong>5. Irosun</strong> — the marketplace, exchange, transactions; the public square.<br>
       <strong>6. Owonrin</strong> — disturbance, instability, things turned upside down; cleansing chaos.<br>
       <strong>7. Obara</strong> — kingship, leadership, royal authority; the burden of rule.<br>
       <strong>8. Okanran</strong> — fierceness, sudden decision, the cutting blade; necessary aggression.<br>
       <strong>9. Ogunda</strong> — Ogun's path; clearing, opening, breaking through.<br>
       <strong>10. Osa</strong> — winds, storms, sudden change (Oya's signature); transformative weather.<br>
       <strong>11. Ika</strong> — bitterness, complexity, knotted situations; what must be untangled.<br>
       <strong>12. Oturupon</strong> — illness, hidden sickness, the body's grievance; what wants healing.<br>
       <strong>13. Otura</strong> — connection, communication, the message that arrives; spirit speaking.<br>
       <strong>14. Irete</strong> — restraint, protection, the held position; defensive wisdom.<br>
       <strong>15. Oshe</strong> — Oshun's signature; love, sweetness, generation, abundance.<br>
       <strong>16. Ofun</strong> — purity, white cloth, Obatala's signature; cool ethical clarity.</p>`,

      `<h3>How They Combine — The 256</h3>
       <p class="no-indent">When a Babalawo casts the opele, the chain falls in <strong>two arms</strong>. Each arm produces one of the sixteen Odu. The two together — the right arm read first, then the left — combine into one of <strong>256 compound Odu</strong>. The compound Odu is the actual reading.</p>
       <p>The way they combine is significant. If both arms produce the same Odu — say Ogbe in both arms — the result is "Ogbe Meji," and the meji ("twin") forms are the <strong>16 most senior Odu</strong>. They are considered the deepest, the most ancient, the most authoritative. When a Meji comes up, the diviner sits straighter. Something foundational is being said.</p>
       <p>If the arms produce different Odu — say Ogbe in the right arm and Oyeku in the left — the result is "Ogbe-Oyeku," a compound Odu with its own specific meaning, drawing on both parents but not reducible to either. There are 240 such compound Odu (16 × 16 minus the 16 Meji). Each has its own verses, its own stories, its own prescriptions.</p>
       <p>This is the elegance of the system: <strong>two simple binary casts — each just a four-bit pattern — generate, by combination, an enormous descriptive vocabulary</strong>. And every one of the 256 has been studied, refined, and verse-equipped by diviners across a thousand years. <em>You are not consulting a single mind. You are consulting an accumulated civilization of pattern-readers.</em></p>`,

      `<h3>An Odu Tells a Story</h3>
       <p class="no-indent">It would help to give you a sense of what an Odu actually <em>says</em>. We will not give a real ese-Ifa (verse) here — the tradition reserves those for trained diviners, and reciting them out of context is considered disrespectful. But we can describe the structure.</p>
       <p>Each Odu, when it comes up in a reading, brings with it a body of <strong>ese-Ifa</strong> — verses, in poetic Yoruba, that the Babalawo recites or paraphrases for the client. Each verse typically has the form: <em>"In the time of so-and-so, when this-and-such happened, the diviner told them to do X. They did X (or did not do X), and the result was Y. The lesson is Z."</em></p>
       <p>The Babalawo, hearing the client's question, selects from the many verses associated with the cast Odu the ones most relevant to this particular client's situation. The selection itself is an act of skill — the verses are not all read; the right ones are read. <strong>This is why Ifa cannot be replaced by a lookup table or an app.</strong> The matching of cast Odu to particular life-situation requires deep human discernment, anchored in the diviner's own seven-plus years of training and ongoing relationship with Orunmila.</p>
       <p>A reading typically runs an hour or more. The client receives stories that obliquely mirror their own situation, prescriptions for offerings and behavioral changes, and warnings about what to avoid. They leave with <em>guidance</em> — not orders, not predictions, but the considered wisdom of a vast inherited library, applied by a trained mind to their particular question.</p>`,

      `<h3>Cowries — The Diaspora's Adaptation</h3>
       <p class="no-indent">Across the Atlantic, where the full Ifa apparatus could not always survive, the diaspora developed <strong>dilogún</strong> — divination using <em>16 cowrie shells</em>. Each cowrie has a "mouth" (the natural opening) and a "back" (the smooth side). When 16 cowries are cast, the count of mouths-up gives a number from 0 to 16, and that number maps to one of the major Odu (with some adaptations specific to the Lucumí tradition in Cuba, Candomblé in Brazil, etc.).</p>
       <p>Dilogún is generally performed by initiated priests of the orisha (an Iyalorisha or Babalorisha), not by Babalawo proper, and it is often associated with consulting the orisha that crowns one's head — Yemoja's diviner reads through Yemoja, Oshun's diviner reads through Oshun, and so on. The system is somewhat simpler than Ifa, but in the houses where it has been preserved (Lucumí Cuba, Candomblé Brazil, Trinidad Orisha), it is robust and respected.</p>
       <p>For the diasporic student, dilogún is often the most accessible form of formal divination — Iyalorisha and Babalorisha are more numerous than Babalawo in many cities, and a dilogún reading can be obtained more readily than a full Ifa consultation. <strong>If you are seeking your first formal reading, dilogún is the appropriate door.</strong></p>`,

      `<h3>What This Module Has Not Taught You</h3>
       <p class="no-indent">This must be said plainly. <strong>You cannot read the Odu after this lesson.</strong> You cannot interpret an opele cast. You cannot give a dilogún reading. The 16-and-256 system is a <em>library</em> the size of a major university's holdings, in oral form, encoded in mnemonic verses that take years to memorize and longer to apply with skill. To pretend otherwise — to start "reading the Odu" for friends after a single course — is the kind of act that makes the elders close the door to the diaspora.</p>
       <p>What this lesson <em>has</em> given you is <strong>conceptual literacy</strong>. When you eventually sit before a Babalawo or Iyalorisha, you will understand the architecture of what they are doing. You will know that the cast names a pattern from a fixed cosmic alphabet. You will know that the verses they recite come from a long-accumulated tradition. You will know to ask: <em>"What Odu came up? What does the verse say? What prescription is suggested?"</em> You will be a <strong>good client</strong>, which is itself a skill, and not a common one.</p>
       <p>If you are called to deeper study — if Orunmila is in fact pulling you toward the priesthood — you will find a teacher. The right teacher finds the student who is ready. <em>Until then, this conceptual literacy and the obi practice you learned in lesson three are sufficient.</em></p>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Two practices, both meditative rather than active:</p>
       <p><strong>Practice 1 — Sit with one Odu.</strong> Choose one of the sixteen from the list above whose phrase struck you. Spend the week noticing where, in your life, that energy is present. If you chose Ogbe (light/openness), where is the morning of an undertaking happening? If you chose Oyeku (endings), what in you wants to die so something new can begin? If you chose Oshe (sweetness), where has love been moving in your life? <em>You are not "casting" the Odu. You are learning to recognize its signature in lived experience.</em></p>
       <p><strong>Practice 2 — Research diviners in your area.</strong> If you are ready, begin to identify legitimate Iyalorisha, Babalorisha, or (if available) Babalawo / Iyanifa in reachable distance. Vet carefully — ask about their lineage, their initiation, the years of their training. The orisha communities in major cities have referral networks. <strong>Do not consult anyone who promises specific outcomes, charges exorbitantly, or operates without lineage.</strong> A real diviner will tell you what they saw and prescribe what the system suggests; they will not promise you wealth or romance.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#5a3a14;">Next chapter: <em>The Diviner's Ethics & Everyday Omens</em> — what to do with what you have heard, and how to read the universe between formal castings.</p>`
    ]
  },

  // ─── LESSON 5 — Ethics & Everyday Omens ─────────────────────
  { id:'d5', name:"The Diviner's Ethics & Everyday Omens", time:'22 min',
    glyph:'◑', x:'70%', y:'78%',
    prompt:'What did the universe show you this week that you almost dismissed?',
    lead:'The deepest divination happens between the casts. Every day is full of signs. The diviner has just learned to notice.',
    excerpt:'The final lesson of this module covers two complementary subjects: the <strong>ethics</strong> the tradition demands of anyone who reads for others (which is more demanding than most students expect), and the <strong>everyday divination</strong> that requires no tools — the practice of reading the constant signs the universe is already sending. After this, you have what you need.',
    pages: [
      `<p class="dropcap no-indent">Every African spiritual tradition that has retained its dignity through the diaspora has done so partly because of strict <strong>ethical codes</strong> binding the diviner. The codes are not optional. They are not historical curiosity. They are the reason the system has authority — and they are the reason untrained practitioners doing tarot-app-style readings do <em>not</em> have authority, even when they are technically pulling cards or shells correctly. The system without the ethics is theatrics. <em>The ethics are what make it real.</em></p>
       <p>This lesson exists because, by now, you have begun obi practice. You may have begun thinking about reading for a friend. You may have considered whether you are called to deeper study. Before you take any of those steps, you need to know what the elders demand of anyone who positions themselves between a person and the spirit world. The bar is high. It should be.</p>`,

      `<h3>The First Ethic — Question What You See</h3>
       <p class="no-indent">A cast comes up. You read the pattern. You feel certain you know what it means. <strong>That feeling of certainty is the moment to slow down.</strong> The trained diviner — the Babalawo of seven years' training — is taught to <em>question their own first read</em>. To ask: am I projecting? Is the question I am answering the question the client asked? Is there another interpretation of this cast that I am missing because of my own bias?</p>
       <p>The untrained reader — and many self-styled "intuitives" online — does the opposite. They feel certainty and they speak it. <em>That is dangerous.</em> Especially if the reader is reading for someone else. A bad reading delivered confidently can damage a person's life — convince them to leave a relationship that should be repaired, take a path that is not theirs, abandon work they were meant to do. The elders are explicit: <strong>a diviner's first responsibility is to do no harm</strong>, and the second is to receive the message accurately. Speed and confidence come last, after years of training have proven them earned.</p>
       <p>For the lay practitioner using obi for personal questions, this becomes: <em>after a cast, sit with it. Ask whether the obvious read is the right read. Consider alternatives. Sleep on it.</em> The cast is a starting point for discernment, not a verdict.</p>`,

      `<h3>The Second Ethic — Confidentiality</h3>
       <p class="no-indent">Whatever is said in a reading stays in the reading. Forever. A Babalawo who gossips about his clients' readings would be barred from practice in any traditional house, and rightly. The reading creates a sacred space; its contents are holy and protected. <em>The diviner is the priest of confidentiality, before they are anything else.</em></p>
       <p>For the lay practitioner, this becomes critical the first time a friend asks you to read for them. <strong>If you cast for someone, you cannot speak about what came up to anyone — not your spouse, not your sister, not the practitioner you are studying with.</strong> Their reading is theirs. The information leaves your mouth only back to them, and only with their permission goes anywhere else.</p>
       <p>This standard is high enough that many serious students of the tradition <em>refuse to read for friends and family at all</em> — recognizing that the relational entanglements make perfect confidentiality nearly impossible. They send their loved ones to a practitioner outside the friendship, where the boundary is structurally clean. <strong>This is wisdom, not avoidance.</strong></p>`,

      `<h3>The Third Ethic — Money and Motive</h3>
       <p class="no-indent">Reading for money is not forbidden in the tradition. Babalawo and Iyalorisha are entitled to compensation for their work — they have spent decades training, the consultation takes hours, the prescriptions sometimes require expensive offerings, and they must eat. <em>Compensation is normal and ethical.</em></p>
       <p>What is forbidden — and the elders are vehement about this — is <strong>charging exorbitantly, advertising specific outcomes, or making the reading transactional in a way that distorts the message</strong>. A diviner who charges $500 and promises you'll find love is selling fantasy, not delivering Ifa. A diviner who tells everyone "you have a curse on you, and for $1500 I can remove it" is running a scam that the tradition specifically condemns.</p>
       <p>Legitimate reading has these signatures: <em>fees are reasonable and clearly stated upfront; outcomes are never promised; prescriptions involve work the client must do (offerings, behavioral changes, ritual), not money paid to the diviner; the diviner is willing to refuse a client if the question is inappropriate or the timing is wrong</em>. <strong>If a "diviner" wants more from you than is reasonable, they are not a diviner.</strong> Walk away.</p>
       <p>For the lay practitioner reading obi for yourself: this means do not commercialize until you are deeply trained. If a friend offers you money for a reading, decline gently, or accept a small token gift only if you are confident in your skill. <em>The financial dimension of divination requires the same care as the divination itself.</em></p>`,

      `<h3>The Fourth Ethic — When to Refuse</h3>
       <p class="no-indent">The trained diviner refuses readings under many conditions. Among them:</p>
       <p><strong>When the client wants confirmation, not truth.</strong> If someone is clearly using the cast to validate a decision they have already made, the diviner has the right (and often the obligation) to refuse. Confirmation seekers do not actually want a reading; they want a stamp.</p>
       <p><strong>When the question is about another person's hidden behavior.</strong> Will my husband cheat on me. Is my friend lying to me. The cowries can speak to your relational situation, but they should not be used to surveil another adult who has not consented to a reading on themselves.</p>
       <p><strong>When the client is in acute crisis.</strong> A reading is not a therapy session. Someone in mental-health crisis, suicidal ideation, or active abuse needs professional help and immediate safety, not a divinatory reading. The ethical diviner says: <em>"This is beyond what the cowries can address. Call this number. Talk to this person. Come back when you are safer."</em></p>
       <p><strong>When the diviner is impaired.</strong> Tired, sick, drunk, deeply emotionally entangled, or having received a difficult reading themselves recently. The cast requires presence. If presence is not available, the cast does not happen.</p>
       <p>Refusing a reading is itself a skilled act. <strong>The diviner who knows when not to cast is more trustworthy than the one who casts in every situation.</strong></p>`,

      `<h3>Everyday Omens — The Divination Without Tools</h3>
       <p class="no-indent">We turn now to the practice that runs alongside formal divination, and which every traditional African elder considered foundational: <strong>the daily reading of signs</strong>. The universe speaks constantly. Most modern people have lost the ability to hear; the African house has not.</p>
       <p>An everyday omen is any pattern in lived experience that <em>arrives uninvited and carries unusual weight</em>. The elders teach four primary categories:</p>
       <p><strong>Animals as messengers.</strong> A bird flies into your window. A snake crosses your path. A cat appears at your door for three days running. The traditional teaching: <em>animals that arrive unbidden are carrying messages</em>, and the species, behavior, and timing all matter. (The full taxonomy is enormous; it varies by region and lineage.) When an animal-message arrives, pause. Ask: <em>what was I just thinking about? What decision was I just making?</em> Often the omen comments on the very thing you were considering.</p>
       <p><strong>Repetitions.</strong> The same number on three different clocks in one day. The same name on three unrelated tongues in one week. A song you have not heard in a decade playing in three different stores. <em>The universe repeats when it is trying to make a point you have been missing.</em> The traditional response: stop, note the repetition, ask what the pattern is pointing toward.</p>
       <p><strong>Dreams that arrive in series.</strong> A single dream is just a dream. A dream that comes back two and three nights running is a <em>communication</em>. The elder dreams with attention to: <em>who appeared? What did they say? What were they doing? What was the emotional temperature?</em> Recurring ancestors, recurring situations, recurring emotional notes — these are messages that have not been received yet and so are being repeated.</p>
       <p><strong>The "exactly the right thing said by the wrong person."</strong> A stranger on the bus says the precise sentence you needed to hear about your relationship. A child you barely know asks the question your therapist has been circling for months. <em>The universe uses unlikely vehicles to deliver important messages</em>, partly because we cannot dismiss them as "what we expected to hear." The traditional diviner welcomes these.</p>`,

      `<h3>How to Read the Day</h3>
       <p class="no-indent">A practice the elders teach for cultivating omen-literacy: at the end of each day, before sleep, do a brief review. Ask: <em>what arrived today that I did not expect? What pattern repeated? What did the universe do to get my attention?</em></p>
       <p>Most days the answer is <em>nothing in particular</em>, and that is fine. But on some days, you will notice — once you start asking — that the day was actually full of signs you walked through without noticing. The bird at the window. The number 222 three times. The ex who texted out of nowhere. The sentence the child said. <strong>The signs were always there. You just hadn't been listening.</strong></p>
       <p>Over months, this practice trains the very organ of perception that formal divination relies on. <em>The diviner who can read the day with accuracy can read the cowries with accuracy. The two are the same skill.</em> Many elders, in fact, do not cast formally for themselves at all — they have become so fluent in everyday omens that the universe answers their questions before the cowries can be reached for. <strong>This is the upper end of the practice.</strong> You are not there yet. But the path runs through this daily noticing.</p>
       <div class="bk-quote">"The signs were always there. You just hadn't been listening."</div>`,

      `<h3>Module IV in Summary, and Your Path Onward</h3>
       <p class="no-indent">You have learned: that divination is structured listening, not fortune-telling. That Orunmila is the orisha behind the system — the witness of every soul's destiny, the librarian of the cosmos. That obi is the simple, accessible casting tool every household once knew. That Ifa proper, with its 16 Odu pairing into 256 compound Odu, is a vast oral library that takes years to master and is held by trained Babalawo and Iyanifa. That the diasporic dilogún (16 cowries) is the most accessible formal door for most diaspora students. That the ethics binding any practitioner are demanding, and rightly. That the deepest divination happens daily, in the reading of unbidden signs.</p>
       <p>Your path onward, as a practitioner of this curriculum:</p>
       <p><strong>Continue obi practice</strong> — sparingly, with weighty questions, recording results, watching your accuracy sharpen.<br>
       <strong>Continue weekly Orunmila greeting</strong> — the kola or coconut, the yellow candle, the five minutes of silence.<br>
       <strong>Cultivate everyday omen literacy</strong> — the end-of-day review, the noticing of repetitions and uninvited messengers.<br>
       <strong>When a major question arises that obi cannot resolve</strong> — find a legitimate Iyalorisha, Babalorisha, or (if available) Babalawo / Iyanifa, and consult them. You will be a good client now.<br>
       <strong>If you are called to deeper study</strong> — let the right teacher find you. They will. Do not hurry it.</p>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Two final practices for this module:</p>
       <p><strong>Daily — the end-of-day review.</strong> Each evening before sleep, take three minutes. Ask: <em>What arrived today that I did not expect? What pattern repeated? What was the universe trying to show me?</em> Note in your journal anything that surfaces. After seven days, read back through. <strong>You will be surprised at how much was there.</strong></p>
       <p><strong>Once during the week — research a real diviner.</strong> Begin the work of identifying a legitimate practitioner in your area or your city. Ask the orisha communities. Read about lineages. Make a note of one or two names you might consult, when the right question eventually comes.</p>
       <p>Module IV is complete. You have crossed the threshold from <em>practitioner who builds altars and tends ancestors</em> to <em>practitioner who has learned the African house's primary tool for hearing what the universe says back</em>. <strong>This is a substantial step.</strong> Sit with it before moving on.</p>
       <p class="no-indent" style="margin-top:32px;text-align:center;font-style:italic;color:#5a3a14;">Module IV complete. Next: <em>Ritual & Ceremony — The Sacred Architecture of Action</em>, where the daily, monthly, and seasonal rhythms of traditional practice come into focus.</p>`
    ]
  }

];
