// ══════════════════════════════════════════════════════════════
// MODULE II — ANCESTRAL VENERATION ("The Bridge of Bones")
//   Five lessons, each ~8 pages, in the same essay-form voice
//   as Module I. Grounded in the curriculum framework:
//     • The Living-Dead (qualifications, transcendent state)
//     • The Bridge of Bones (physical conduits, graveyard dirt)
//     • The Technology of Veneration (Mojuba, dreams, reliquary)
//     • Corrective Rituals (Clearing of the Village, healing the dead)
//     • Iwa-pele as inheritance (13 guidelines)
// ══════════════════════════════════════════════════════════════
window.MODULE_2_LESSONS = [

  // ─── LESSON 1 — The Altar as Threshold ────────────────────────
  { id:'a1', name:'The Altar as Threshold', time:'18 min',
    glyph:'☩', x:'50%', y:'46%',
    prompt:'What does it mean to be remembered?',
    lead:'Before there was a word for religion, there was the altar. A doorway between the seen and the unseen, kept warm by attention.',
    excerpt:'In Africana traditions, the ancestors are not <em>gone</em> — they are the <strong>living-dead</strong>, residing in a state of transcendence between Olódùmarè and humankind. The altar is the <strong>threshold</strong> across which we tend that relationship. Not a stage for petition. A doorway, kept warm by water, white cloth, candle, and the steady act of <em>showing up</em>.',
    pages: [
      `<p class="dropcap no-indent">The altar is the oldest invention of our people. Older than language as we know it. Older than the wheel. Older than nation, tribe, or border. A flat stone. A handful of soil. A shell. A name spoken aloud — and the world becomes <strong>hinged</strong>. One side: what you can touch. The other: what touches you back.</p>
       <p>In the Yoruba imagination, the altar is called <em>ojúbọ</em> — literally, "the face of worship." But the older meaning, the one our grandmothers carry in their hands when they set a glass of water down at dusk, is closer to <strong>face-of-meeting</strong>. The altar is where two faces look at each other across the veil. The living face. The face that has gone on.</p>
       <div class="bk-quote">"The altar is not a stage for petition. It is a threshold."</div>
       <p>What this means, practically, is that we do not <em>go to</em> the altar to perform. We go to <strong>arrive</strong>. To set down the day. To be witnessed by those who knew us before we had names. <em>Religion</em> is a recent word. <em>Threshold</em> is an old one.</p>`,

      `<h3>The Living-Dead</h3>
       <p class="no-indent">Before we go further, we must rename what most of us were taught to call <em>the dead</em>. In our framework, those who have crossed the threshold and remain in active relationship with the lineage are not "the dead." They are the <strong>living-dead</strong> — spirits of human beings who lived <em>morally upright lives</em>, who died what is called a <em>good death</em>, and who received <em>proper funerary honors</em>. They reside in a state of <em>transcendence</em>, suspended between the Supreme Being and the human marketplace, available as guides, witnesses, and intercessors.</p>
       <p>The phrase is borrowed from John Mbiti, but the idea is far older than the phrase. Across nearly every African tradition, the elders insist on the same teaching: <strong>the ancestor is more alive than you are</strong>. They have shed the body's distractions. They see further. They remember more. They are not pining for life. They are <em>living a different stage of life</em> — and they remain part of the family they left behind.</p>
       <p>If you carry, even faintly, the inherited Western sense that the dead are <em>diminished</em> — ghostly, sad, less-than — let that go now. <em>It is a stolen idea, and it does not belong to you.</em> The grandmothers you came from believed something more accurate, and more useful: <strong>the ancestor is the elder. Always. Without exception.</strong></p>`,

      `<h3>Who Becomes an Ancestor?</h3>
       <p class="no-indent">This is the question modern students most often whisper to themselves: <em>does my person qualify?</em> And it is the question the elders answer most carefully. To be venerated as a full ancestor in the traditional sense — not merely remembered, but <em>elevated</em> and available to the lineage — three conditions are typically named:</p>
       <p><strong>One: a ripe old age.</strong> The traditional ancestor lived long enough to accumulate wisdom. They saw children and grandchildren. They had time to make mistakes and time to redress them. They were a <em>completed person</em>, not an interrupted one.</p>
       <p><strong>Two: a good death.</strong> A death that was not by suicide, not from certain feared illnesses (the elders speak of leprosy, smallpox, and similar wasting diseases), and not by violent or shameful means. <em>Why?</em> Not because such deaths make the soul unworthy — they do not. But because such deaths leave the soul <strong>turbulent</strong>, requiring more ritual labor from the living before the elevation can complete.</p>
       <p><strong>Three: proper funerary honors.</strong> The body washed. The name spoken. The community gathered. The libations poured. The grave attended.</p>
       <p>Now — and this matters — <em>most of our people in the diaspora did not get all three</em>. Many died young. Many died in violence. Many were buried unmarked. <strong>This does not exclude them.</strong> It simply means the living have <em>more elevation work to do</em>. We will return to this in lesson four. <em>No one is beyond the reach of love poured backward through time.</em></p>`,

      `<h3>The Path of Memory</h3>
       <p class="no-indent">There is a teaching across several African traditions — particularly strong among the Akan and Yoruba — that <strong>every birth is the arrival of an ancestor returning to fulfill an unfinished task</strong>. The infant has just crossed the river the other way. They are not blank. They are <em>arriving with cargo</em>: a personality, a destiny, a continuation of work the lineage has been doing for centuries.</p>
       <p>This is why, in some traditions, the grandfather and grandson are said to share a <em>secret protocol</em>. The newborn arrives with the news of the unseen world fresh in their bones — the smell of where they came from, the names of those they sat among. The grandfather, the closest living person to the threshold himself, has the duty to <em>receive that news</em> before the child forgets. He whispers to the baby. He listens for what the baby seems to know. The protocol is fast: within months, the child will lose conscious access to where they came from. <strong>The wisdom must be received before it submerges.</strong></p>
       <p>You may not have had this transmission. Most of us did not. The grandfather you needed was working three jobs. The grandmother you needed was eight states away. The protocol broke. <em>This too can be repaired.</em> An adult, sitting at an altar, with a notebook and a willingness to listen, can recover much of what was supposed to come through at birth. <strong>The threshold is patient. It will tell you, eventually, what you came here to do.</strong></p>`,

      `<h3>What an Altar Is Not</h3>
       <p class="no-indent">It is not a wishing well. It is not a vending machine into which you insert prayer and from which you receive results. It is not, despite four hundred years of Hollywood, a <em>frightening</em> place. The altar is a <strong>kitchen</strong>. A place of slow tending. A place where soup is made over hours by a woman who has fed her people for fifty years and knows the difference between rushing and stirring.</p>
       <p>It is also not a place of <em>performance</em>. You do not need to be eloquent at the altar. You do not need to bring impressive offerings. You do not need to know the right Yoruba words. The altar is <strong>indifferent to spectacle</strong> and <em>responsive to consistency</em>. A glass of water, set down with intention, beats an elaborate ritual performed once and abandoned.</p>
       <h3>What an Altar Is</h3>
       <p class="no-indent">It is the most honest mirror you will ever build. Whatever you place on it — bread, water, a photograph, a coin, a letter — becomes a small confession. <strong>This is who I am thinking of. This is who I am willing to remember. This is what I have to give today, and that is enough.</strong></p>
       <p>It is also, in our framework, a <em>tuning fork</em>. The objects on it are not symbols. They are <strong>frequency markers</strong>. A glass of water hums at one frequency; a white candle at another; a photograph at a third. The combination calls to the ancestors at <em>their</em> frequency. They recognize the tuning. They come because they were called <em>in their own language</em>.</p>`,

      `<h3>Altars in Hidden Places</h3>
       <p class="no-indent">Across the diaspora, we have built altars in every condition the world tried to forbid them. <em>In slave quarters.</em> In tenement closets. On hospital nightstands. On the dashboards of long-haul trucks. Under the kitchen sink, behind the cleaning supplies. The altar travels because <strong>we</strong> traveled. The altar hides because <strong>we</strong> had to hide. And the altar still works, even hidden — because the ancestors do not require ceremony. They require <em>recognition</em>.</p>
       <p>If you live in a household where open ancestor work would create conflict — a Pentecostal partner, a Muslim parent, a roommate who would not understand — know this: <strong>your altar can be small enough to fit in a drawer</strong>. A folded handkerchief. A small glass. A penny. A name written on a slip of paper. Closed at sunrise, opened at night. The grandmothers worked under worse conditions than yours. The work still got done.</p>
       <div class="bk-quote">"The altar travels because we traveled. The altar hides because we had to hide. The work still gets done."</div>`,

      `<h3>Three Truths to Carry</h3>
       <p class="no-indent">The first: <strong>the altar is not built — it is recognized.</strong> Wherever you set down a glass of water with intention, an altar has appeared. The objects are not what makes it sacred. The <em>attention</em> is.</p>
       <p>The second: <strong>the altar does not require initiation.</strong> Some traditions have priesthoods, lineages, formal openings. Those are precious. They are also not the only door. A grandmother lighting a candle for her dead son in 1923 was not initiated, and the candle still reached him. <em>Initiation deepens the work; it does not gatekeep the work.</em></p>
       <p>The third: <strong>the altar wants nothing from you that you do not already have.</strong> Water from your tap. A flower from your walk home. A photograph from your phone, printed at the drugstore. A song hummed under your breath. The altar is not impressed by money. The altar is impressed by <em>showing up</em>.</p>`,

      `<h3>The Restless Modern</h3>
       <p class="no-indent">Before we leave this first lesson, one more teaching the elders insist on: <em>the restlessness of the modern person is, in large measure, a symptom of broken ancestral relationship</em>. The free-floating anxiety. The chronic feeling of not belonging. The inability to settle. The sense that <em>something is supposed to be there and isn't</em>. These are not character flaws. They are the absence of a particular kind of nourishment — and the altar is where that nourishment is delivered.</p>
       <p>In African thought, you are not, fundamentally, an isolated individual. You are <strong>a cell in a larger ancestral body</strong>. When the cell is severed from the body, the cell becomes restless, vulnerable to disease, prone to forgetting its purpose. The work of altar tending is not piety. It is <em>reattachment</em>. <em>It is medicine for a wound you may not have known you carried.</em></p>
       <h3>Your Practice This Week</h3>
       <p class="no-indent">Find a flat surface in your home that you pass <strong>at least three times a day</strong>. Not the showy spot. Not the entryway you've been told altars belong in. The <em>real</em> spot — the corner of your kitchen, the top of your dresser, the windowsill above the sink. Wherever your eyes already rest.</p>
       <p>Put down a single white cloth. On top of the cloth, place one glass of clear water. Beside the water, one item that names a person you wish to remember — a photograph if you have it, a written name on a slip of paper if you don't. Light no candle yet. Burn no incense yet. Just <strong>this</strong>.</p>
       <p>For seven days, every time you pass, slow down for the length of one breath. That is the whole practice. We are not building an altar this week. We are <em>noticing</em> a threshold that has been there all along.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#6a3a14;">In the next chapter — <em>White Cloth & Clear Water</em> — we will dress the altar fully and meet the Mojuba.</p>`
    ]
  },

  // ─── LESSON 2 — White Cloth & Clear Water ────────────────────
  { id:'a2', name:'White Cloth & Clear Water', time:'20 min',
    glyph:'☖', x:'30%', y:'58%',
    prompt:'Whose name will you set down in water this week?',
    lead:'White cloth. Clear water. A single white candle. The bones of an altar four hundred years old.',
    excerpt:'<strong>White cloth.</strong> <strong>Clear water.</strong> <strong>A single white candle.</strong> This is the foundation of an ancestral altar — and it has lived in the kitchens, closets, and corners of Black women across the diaspora for four centuries. The simplicity is the point. Today we also meet the <em>Mojuba</em> — the libation prayer that opens every traditional working.',
    pages: [
      `<p class="dropcap no-indent">When my grandmother set up her altar — though she would never have called it that, she would have said <em>"my little corner"</em> — she used a white pillowcase folded in quarters. A water glass that had once held jelly. A votive candle from the Catholic supply store on Claiborne Avenue. A photograph of her own mother, in a wooden frame from a thrift store, the glass cracked diagonally across one corner. That was it. That was the entire arrangement. And I am here, two generations later, because <strong>that arrangement worked</strong>.</p>
       <p>This is the most important thing I can tell you about ancestral altars: <em>they were never about the objects</em>. The objects are <strong>names for attention</strong>. A white cloth is a name. A glass of water is a name. A candle is a name. Each one says, in the silent language of objects: <em>I am paying attention here. This patch of the world is consecrated to remembering.</em> The ancestors do not need fancy. The ancestors need <strong>consistent</strong>.</p>
       <div class="bk-quote">"The objects are not the altar. The attention is."</div>`,

      `<h3>Why White Cloth</h3>
       <p class="no-indent">White, in nearly every Africana spiritual tradition, is the color of the ancestors. <em>Why?</em> Several reasons, woven together. White is the absence of disturbance — a clean canvas onto which the unseen can land. White holds light evenly, which the elders say helps the spirits <em>see</em> the offering. And in the West African textile tradition, white was the cloth of mourning, of priesthood, of crossing — the fabric you wore when you were moving between worlds.</p>
       <p>Across the Atlantic, in Cuba, Brazil, Trinidad, and Louisiana, white survived all the suppressions and re-emerged. The <em>iyaworaje</em> — the year-and-seven-days that newly-initiated Lucumí priests spend dressed entirely in white. The <em>vestido</em> of the Brazilian priestess. The Spiritual Baptist robes. The white sheet a Hoodoo woman in 1940s Mississippi spread under the wash basin before working over a client. <strong>White is the color the ancestors recognize.</strong> They have been seeing it on us for a long time.</p>
       <h3>Why Clear Water</h3>
       <p class="no-indent">Water is the most ancient offering on earth. It existed before incense. Before flowers. Before fire. Water is what every ancestor of every human person knew intimately — they drank it, washed in it, fled across it, drowned in it, were baptized in it. To set a glass of water on an altar is to offer the ancestors the one thing every single one of them has wanted at some point.</p>
       <p><em>It is also a mirror.</em> When you place water on the altar, the ceiling of your home is reflected in it — and the elders say this is how the ancestors <strong>look up at you from below</strong>. The water is a window in both directions. It is also the <em>cooling agent</em>. Restless or unelevated spirits are described as "hot"; water cools them, settles them, allows them to receive the prayer being offered.</p>`,

      `<h3>Why a Single White Candle</h3>
       <p class="no-indent">Fire is the messenger. In nearly every African tradition, fire is what carries the prayer from the world of the living to the world of the unseen. Smoke rises. Light travels. The candle is small, but it is the <em>postal service</em> of your altar.</p>
       <p>One candle is enough. Do not let anyone tell you that you need seven, or thirteen, or a specific brand from a specific shop. <strong>One candle, lit with intention, will do the entire work.</strong> The candle's job is to mark the duration of the visit — when it is lit, the door is open; when it is snuffed, the door rests.</p>
       <p>One small but important detail the elders insist on: <em>do not blow out the candle.</em> Use a snuffer, a metal lid, or your fingers (carefully) to extinguish it. <em>Why?</em> The traditional teaching is that breath blows the prayer back at you and scatters the message. The folk explanation is gentler: <em>you would not blow into your grandmother's face. Do not blow into her candle.</em></p>`,

      `<h3>The Mojuba — Pouring of Libation</h3>
       <p class="no-indent">Now we meet the most universal ancestral practice in the African world. The <strong>Mojuba</strong> (in Yoruba; called by other names in other traditions, but the action is the same): the <em>pouring of libation</em>. Before any major endeavor — a meeting, a journey, a working, a meal of importance — water (or sometimes beer, palm wine, whiskey) is poured to the ancestors as homage. <em>You drink last. They drink first.</em></p>
       <p>The Mojuba is the central act of African and Africana ancestor reverence. It says, <strong>before I move, I acknowledge those who made my movement possible</strong>. Before I claim any of this, I pour for those who never got to claim it. Before I drink, my elders drink. <em>This single gesture, repeated daily, rewires the modern self away from individualism and back toward lineage.</em></p>
       <p>You can pour to the houseplant. You can pour to the tree pit on your block. You can pour to the bottom of the white cloth. The earth receives all libation. <strong>The ancestors are reached through whatever ground you pour onto, because the ground itself is Onile — the great mother who holds them all.</strong></p>
       <div class="bk-quote">"Before I move, I acknowledge those who made my movement possible. The ancestors drink first."</div>`,

      `<h3>How to Set It Up — Right Now, Today</h3>
       <p class="no-indent">You need: one piece of white cloth (a pillowcase, a handkerchief, a kitchen towel — washed clean). One glass — clear, not colored, ideally with no etching or printing. Tap water, fresh, room temperature. One white candle, any size. Optionally: a photograph or a written name on a slip of paper. Optionally: a small bowl or saucer for offerings.</p>
       <p>Choose your spot. (See lesson one — the spot you pass three times a day, not the showy spot.) Lay the cloth flat. Place the glass of water in the center. Place the candle to the right of the water. Place the photograph or name behind the water, leaning gently against the wall. <strong>That is the altar.</strong> You are done.</p>
       <h3>Black-Eyed Peas in the Four Corners</h3>
       <p class="no-indent">A traditional ancillary practice from across the African American South: place a small handful of dried <strong>black-eyed peas in each of the four corners of your home</strong>, just inside the door, behind a piece of furniture, wherever they will not be disturbed. Black-eyed peas are an ancestral food — carried across the Middle Passage in the hair of African women — and in this practice they serve two functions: they invite <em>luck</em> across your threshold, and they release accumulated <em>negative energy</em> from the corners where it pools.</p>
       <p>Refresh them seasonally — every three months, pour the old peas onto the earth and replace with new. <em>The corners of your home are not abstract; they are spiritual hinges.</em> A handful of black-eyed peas lubricates them.</p>`,

      `<h3>The Daily Tending</h3>
       <p class="no-indent">Three small acts, woven into the rhythm of your day, and you have a living altar:</p>
       <p><strong>Morning:</strong> Greet the altar. Place your hand briefly near (not on) the water glass. Say one ancestor's name aloud. Pour a tiny libation if you can — even a few drops onto a houseplant counts. <em>That is enough.</em></p>
       <p><strong>Evening:</strong> Light the candle for as long as you are home and awake. Let it burn down naturally if it is small; snuff it (do not blow it out) before bed if it is not. Sit with it for one to three minutes. Speak a name. Listen.</p>
       <p><strong>Once a week — your choice of day:</strong> Pour out the old water onto the earth (a houseplant, a yard, a tree pit on your block). Wash the glass with cool water — no soap, ideally. Refill with fresh water. <em>This is the most important act.</em> <strong>Stagnant water on an altar is not honoring — it is forgetting.</strong> Fresh water is the heartbeat of the practice.</p>
       <div class="bk-quote">"Stagnant water is forgetting. Fresh water is the heartbeat of the practice."</div>`,

      `<h3>What If I Cannot Have a Candle?</h3>
       <p class="no-indent">A real question many students ask, especially those in dorms, sober-living houses, hospital beds, or apartments with strict fire codes. The answer is gentle and practical: <strong>an electric tea light works</strong>. A flashlight pointed upward at the ceiling works. A solar garden light, brought in from outside at sundown and placed beside the water, works. The ancestors have adapted to every condition we have lived in for four hundred years — they will adapt to your apartment lease.</p>
       <p>What matters is not the flame's literal heat. What matters is the <em>marker of presence</em> — something that says, <em>this hour belongs to remembering</em>. The light, in whatever form, is the marker. <strong>The ancestors are not literalists.</strong></p>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Build the bones. White cloth. Clear water. One white candle (or substitute). Optional: black-eyed peas in the four corners. Set it up tonight. Tend it for seven days. Do not add anything. Do not Pinterest it. Do not buy crystals. Do not feel small for how plain it looks. <strong>Plain is the point.</strong> Your great-grandmother's altar was plain. Yours can be too.</p>
       <p>Each evening, before lighting the candle, pour a small libation — a teaspoon of water onto a houseplant or out the back door — and say aloud: <em>"Before I drink, you drink. Before I move, I thank you. Before I rest, I remember."</em> This is your first Mojuba. <strong>Do it for seven days. Notice what changes in how you feel about your home, your morning, your sleep.</strong></p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#6a3a14;">Next chapter: <em>Speaking Their Names</em> — and learning the secret of the bone, the dirt, and the threshold of the grave.</p>`
    ]
  },

  // ─── LESSON 3 — Speaking Their Names & The Bridge of Bones ───
  { id:'a3', name:'Speaking Their Names & The Bridge of Bones', time:'22 min',
    glyph:'⚜', x:'70%', y:'58%',
    prompt:'Say one ancestor\'s name aloud, three times. What stirs?',
    lead:'A name spoken aloud is the oldest spell our people ever cast. And the dirt beneath their feet is a road we can still walk.',
    excerpt:'In the African understanding, <strong>physical remains are conduits</strong> — bones, hair, the very dirt in which a body has rested. This is the <em>Bridge of Bones</em>: the teaching that the dead do not haunt locations the way European ghosts do; they remain reachable through the <strong>physical matter that knew them</strong>. Today we learn to speak their names — and to honor the soil they returned to.',
    pages: [
      `<p class="dropcap no-indent">There is a Yoruba proverb so old that no one remembers who first said it: <em>Ọmọ ti a kò pè l'órúkọ kò ní wá.</em> "The child who is not called by name will not come." It is, on its surface, about disciplining children — call them properly and they will respond. But the elders use it for something deeper. <strong>What you do not name, you cannot summon. What you cannot summon, you cannot receive from.</strong> The name is the rope you throw across the veil.</p>
       <p>This is why, in nearly every African ceremony — birth, naming, initiation, burial, ancestral offering — the <em>recitation of names</em> is central. The lineage is sung. Each ancestor, four, five, sometimes seven generations back, is named aloud, in order, by an elder who memorized the chain when she was still small. The naming is not nostalgia. It is <strong>infrastructure</strong>. The lineage is a chain of names; if a link goes unspoken too long, that part of the chain weakens. The work of the living is to <em>keep the names warm</em>.</p>
       <div class="bk-quote">"What you do not name, you cannot summon."</div>`,

      `<h3>Why the Diaspora Is in Pain</h3>
       <p class="no-indent">For those of us in the diaspora — descendants of the African captives carried across the Atlantic — there is a particular wound here. The slave traders did not just steal bodies. <em>They stole names</em>. The first violence was renaming. A woman whose grandmother had named her Adé became Polly on a Virginia plantation. A boy called Kofi became George. The names were not idle — they carried lineage, town, day-of-the-week, ancestral protection. To strip the name was to attempt to strip the <strong>cord</strong> back to the people who could protect that life.</p>
       <p>It did not work. It never works completely. The names hid in nicknames, in middle names, in the rhythm of how a grandmother called a child for supper. They hid in the songs. They hid in the dishes. But the surface-level loss is real, and many of you carry it: <em>"I do not know my African name. I do not know the names of my great-grandparents. I do not know what to say."</em></p>
       <p><strong>Here is the answer, and it is gentler than you fear:</strong> the ancestors will accept the names you have. Polly will come if you call Polly. George will come if you call George. The slave traders did not have the power to break the cord — only to make it harder to find. Speak the names you know, with love, and the older names you do not know will, in time, <em>introduce themselves</em>. They always do.</p>`,

      `<h3>The Bridge of Bones</h3>
       <p class="no-indent">Now we come to a teaching that distinguishes African ancestral thought from much of European folk belief. In Europe, the dead are thought to <em>haunt locations</em> — a particular castle, a particular crossroads, the house where they died. In Africana traditions, the picture is different. The dead are linked, primarily, to <strong>physical remains and to the matter they passed through</strong>: bones, hair, fingernail clippings, and especially <em>the dirt in which their body has decomposed</em>.</p>
       <p>This is what the elders mean by the <strong>Bridge of Bones</strong>. The body, even after the soul has elevated, retains a <em>resonance</em> with the soul that wore it. The bone is not nothing. The dirt that received the body is not just dirt. These are <em>conduits</em> — points where the living can reach across the threshold and touch the elevated dead with unusual directness.</p>
       <p>In the West African and especially Bakongo (Central African) tradition, this is why <em>graveyard dirt</em> is a working substance — not symbolic, but <strong>operative</strong>. In the Hoodoo tradition that descended from these West and Central African roots, graveyard dirt remains one of the most powerful materials in the cabinet. <em>Used with care. Used with payment. Used with respect.</em></p>
       <div class="bk-quote">"The bone is not nothing. The dirt that received the body is not just dirt. They are conduits."</div>`,

      `<h3>Buying Dirt — The Protocol</h3>
       <p class="no-indent">Because graveyard dirt carries the active resonance of a soul, you cannot simply <em>take</em> it. To take without exchange is theft, and the ancestor whose dirt you stole will know — and will not be of help to you. Across our traditions, the protocol is precise: <strong>you must buy the dirt</strong>. Make an offering. Receive consent. Then remove what you came for.</p>
       <p>The traditional payment varies by region and lineage but converges on a few forms: <em>liquor</em> (a small pour of whiskey, rum, or gin onto the grave), <em>coins</em> (silver dimes are particularly common in Hoodoo — three, seven, or nine of them), <em>tobacco</em> (a single cigarette or a pinch of loose leaf placed on the headstone), or <em>a flower</em> (one stem, fresh, laid at the head). <strong>Always pour to the head, never to the foot.</strong></p>
       <p>You speak to the soul whose grave you are visiting. <em>"Brother, sister, mother — I have come to ask for help. I bring you this offering. If you are willing, allow me to take a small handful of this earth. I will use it for [name your purpose]. I thank you."</em> Then wait. The elders teach that you will <em>feel</em> consent, or not. If you feel a hesitation, a coldness, a sense of <em>"do not"</em> — you leave. You try another grave. <strong>The dead have agency. They are not vending machines.</strong></p>`,

      `<h3>What Graveyard Dirt Is For</h3>
       <p class="no-indent">In the practical tradition, dirt taken with consent is used in three primary ways: <strong>protection</strong> (sprinkled at the threshold of the home, mixed into a mojo bag, or kept in a small jar on the altar), <strong>healing</strong> (mixed into a bath or sprinkled on a wound — physical or spiritual — when the deceased was a healer in life), and <strong>justice work</strong> (when the deceased was a person of moral force in their lifetime, their dirt can be enlisted to bring rightness to a crooked situation).</p>
       <p>What dirt is <em>not</em> for: cursing, harming the innocent, or any working that the deceased would have refused to participate in while alive. The elders are clear: <em>the soul retains its character after death</em>. A grandmother who never harmed anyone in life will not harm anyone for you in death. <strong>Match the working to the soul.</strong> If you need protection, go to a fierce protector's grave. If you need calm, go to a peacemaker's grave.</p>
       <h3>If You Cannot Visit a Grave</h3>
       <p class="no-indent">Most members of the diaspora do not know where their oldest ancestors are buried. The graves were unmarked. The records were burned. The lineage was scattered. <em>This does not exclude you from the Bridge of Bones</em>. There is a substitute the elders developed for exactly this circumstance — and we will meet it in the next chapter.</p>`,

      `<h3>How to Speak Their Names — A Working Protocol</h3>
       <p class="no-indent">There is no perfect script. There is no required language. But here is a structure that has worked for our people for centuries:</p>
       <p><strong>Stand before the altar.</strong> Light the candle. Take three slow breaths.</p>
       <p><strong>Begin with gratitude, not request.</strong> "I thank you for the life that made my life."</p>
       <p><strong>Speak the names, slowly, with space between them.</strong> Mother. Mother's mother. Father. Father's father. As far back as you know. If you only know two names, speak two names. <em>The ancestors are not auditing your records.</em></p>
       <p><strong>Add the unknowns.</strong> "And to the names I do not know, the ones whose names were taken — I greet you also. I am here. I am still here."</p>
       <p><strong>Add the lost ones.</strong> "And to those who died young, who died hard, who did not get the burial they deserved — I see you. I am tending you now. I will keep tending you."</p>
       <p><strong>Close.</strong> "I love you. I am listening. I will return tomorrow." Touch the cloth. Walk away.</p>
       <div class="bk-quote">"Speak the names you have. The older names will, in time, introduce themselves."</div>`,

      `<h3>The Three-Times Rule</h3>
       <p class="no-indent">Many traditions, including Yoruba, hold that a name spoken <strong>three times</strong> carries different weight than a name spoken once. Once is recognition. Twice is greeting. Three times is <em>summons</em>.</p>
       <p>When you wish to feel an ancestor most fully — when you are about to make a hard decision, or you need their counsel before sleep, or you are heading into a difficult day — speak the name three times slowly, with a full breath between each. <em>Mary. Mary. Mary.</em> By the third utterance, you will feel the room change. <strong>This is not imagination. This is literacy returning to a body that always knew how to read.</strong></p>
       <p>You may also use the three-times rule with <em>collective</em> names: "the mothers." "The fathers." "The grandmothers of my line." Spoken three times, slowly, these collective names summon the entire body of the unnamed.</p>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Each evening, at your altar, after you have lit the candle and poured your libation, speak the names of <strong>three ancestors</strong> aloud. The same three each night, or different ones — your choice. Do not perform. Do not whisper out of embarrassment. Speak them at the volume you would use to call a child in for supper. Loud enough to be <strong>heard from the next room</strong>.</p>
       <p>If the ancestors of your blood are unknown, speak collective names: "the mothers of my line." "The fathers of my line." "The ones whose names were taken." On the third night, add one specific name from outside your direct lineage — a deceased mentor, an elder you knew, a public figure who shaped you. <em>Lineage is wider than blood.</em> The ancestors include those who taught you, not only those who bore you.</p>
       <p>By the seventh night, one of them will visit you in a dream, on the street, in a song on the radio. Pay attention. They are answering.</p>
       <p class="no-indent" style="margin-up:24px;margin-top:24px;text-align:center;font-style:italic;color:#6a3a14;">Next chapter: <em>Tending Without Fear</em> — including the reliquary technique for when you do not know where your dead are buried.</p>`
    ]
  },

  // ─── LESSON 4 — Tending Without Fear & Healing the Lineage ───
  { id:'a4', name:'Tending Without Fear & Healing the Lineage', time:'24 min',
    glyph:'⚘', x:'18%', y:'70%',
    prompt:'What fear comes up when you imagine tending the dead? Whose unhealed grief lives in your line?',
    lead:'The well-tended ancestor is a coach, not a haunting. And the unelevated dead can still be healed — by you, today, four hundred years late.',
    excerpt:'Hollywood taught us to fear the dead. Africana traditions teach the opposite — that the <strong>well-tended ancestor is a fierce protector</strong>. Today we also learn the <em>Blackhawk-in-the-Bucket</em> reliquary technique for unmarked graves, and we begin the most reparative work in the tradition: <strong>healing the unelevated ancestors</strong> who could not be properly grieved in their time.',
    pages: [
      `<p class="dropcap no-indent">If you have hesitated to begin this work — if every time you set up the altar a small voice asks <em>"what if I open something I cannot close?"</em> — you are not alone, and you are not wrong to ask. You are participating, without knowing it, in a <strong>four-hundred-year campaign</strong> to make Black people afraid of their own dead.</p>
       <p>The campaign was not accidental. The colonizers knew that a people in conversation with their ancestors are <em>ungovernable</em>. The ancestors give counsel that does not align with the master's interests. They tell the enslaved woman to run. They tell the enslaved man that he is more than property. They remind the children of their <strong>real name</strong>. So the ancestors had to be slandered. Recast as demons. As ghosts. As "voodoo." As something to be exorcised by the new religion. Movies were made. Books were written. Sermons were preached. Generations of Black mothers told their daughters: <em>"do not mess with that mess."</em></p>
       <div class="bk-quote">"A people in conversation with their ancestors is ungovernable. That is why the slander was necessary."</div>
       <p>The slander worked. It is, perhaps, the most successful spiritual heist in modern history. But the heist is being <em>reversed</em>, in your generation, in your kitchen, on the white cloth you laid down last week. <strong>You are part of the reversal.</strong></p>`,

      `<h3>What the Dead Actually Are</h3>
       <p class="no-indent">In Africana traditions, the dead are not a category. They are a <strong>spectrum</strong>. There are <em>well-elevated ancestors</em> — souls who lived with integrity, completed their work, and now reside in a peaceful state from which they can offer real help. There are <em>unelevated dead</em> — souls who died in trauma, confusion, or unfinished business, and who need the prayers of the living to <strong>rise</strong>. There are <em>nameless dead</em>, lineage dead, place-dead, road-dead. Each has its own protocol.</p>
       <p>What this means, practically: <strong>not every spirit you encounter is your ancestor</strong>, and not every ancestor is fully elevated. This is the part nobody wants to hear, but the elders insist on it: <em>tending requires discernment</em>. You are not opening a door to "everything." You are opening a door to <strong>your people</strong> — and you are doing it in a way (white cloth, clear water, named ancestors, a single candle) that the lineage itself recognizes and shapes around.</p>
       <p>The Dagara teacher Malidoma Somé taught this most clearly. <strong>An ancestor who was a "killer or marauder," an ancestor who was not properly grieved, an ancestor whose death tore the family apart and was never spoken of</strong> — that ancestor's unprocessed energy can sit on the lineage and cause illness, addiction, repeated misfortune in their descendants. <em>Until someone, somewhere, chooses to do the healing work.</em></p>`,

      `<h3>The Three Protections That Are Built In</h3>
       <p class="no-indent">When you set up an altar according to the bones — white cloth, clear water, the named dead — you have automatically activated <strong>three protections</strong> that your ancestors gave us long before we knew we would need them:</p>
       <p><strong>1. The named are invited; the unnamed are not.</strong> Spirits work by invitation in the structures of African ritual. You are not throwing open the doors. You are sending specific letters to specific addresses. <em>The altar is a guest list, not a public square.</em></p>
       <p><strong>2. Water is a mirror and a filter.</strong> Across nearly every African and diaspora cosmology, water reflects what is willing to be seen and refuses what would harm. The clear glass is not decoration. It is a <em>working sentry</em>. It will fog, cloud, or develop bubbles when it has filtered something — read it as you would read a newspaper.</p>
       <p><strong>3. Your own Ori is your bouncer.</strong> Remember Ori from the Cosmology module — the inner head, the divine self, the part of you that chose this life. Your Ori knows who is family. It has the final say on who is welcomed. You can trust it. <em>You were always meant to.</em></p>
       <div class="bk-quote">"Fear is not the gatekeeper. Forgetfulness is."</div>`,

      `<h3>The Separate Altar Rule</h3>
       <p class="no-indent">A protocol the elders insist on, and one that is particularly important for the diaspora: <strong>do not mix your ancestors with those who oppressed them on the same altar</strong>. If a slaveholder bears your surname, that slaveholder is not on your ancestor altar. If a man married into your family and abused your grandmother, he is not on the altar. If your line includes betrayers, traitors, or violators of the children — they are not on the altar.</p>
       <p>This is not bitterness. This is <em>infrastructure</em>. An altar's effectiveness depends on its <strong>coherence</strong> — the people on it have to be people you can welcome with a clean heart. To force your great-great-grandmother to share altar space with the man who raped her is to make the altar a place of <em>continued violation</em>. <em>Build her her own clean place.</em></p>
       <p>If you have ancestors of complicated character — a parent you have unfinished business with, an uncle whose harm you are still processing — they may belong on a <strong>separate altar</strong>, away from the main one, where you can do the specific reconciliation work without contaminating the line. Some practitioners keep this second altar in a different room, lower than the main altar, with its own glass of water and its own specific intention: <em>"You are remembered. You are being healed. You are not yet welcome at the main table."</em></p>`,

      `<h3>Healing the Unelevated Dead</h3>
       <p class="no-indent">Here we arrive at one of the deepest workings the tradition offers. The teaching is this: <strong>the diaspora is full of unelevated dead</strong>. People who died in the Middle Passage and were never named. People who died in the fields and were buried without ceremony. People who died young, in violence, in addiction, in despair — and whose families could not, for whatever reason, give them the elevation rites their souls required. <em>These souls are not in torment. But they are not at rest.</em> They sit, suspended, in a state the Dagara call "the side of the road" — neither here nor fully there.</p>
       <p>And here is the radical teaching: <strong>you, the living, can elevate them. Today. Four hundred years late.</strong> The work is called, variously, "elevation work," "ancestral healing," or "lifting the dead." It is among the most reparative spiritual labors a Black person can perform. It is also the source of <em>visible improvement</em> in the lives of the living who do it. Restless ancestors at rest mean restless descendants at peace.</p>
       <div class="bk-quote">"You can elevate them. Today. Four hundred years late. The dead are not beyond reach."</div>`,

      `<h3>The Elevation Working — A Beginner's Form</h3>
       <p class="no-indent">A simple, traditional form for elevating an unelevated ancestor — one you knew, or one you only know by name, or one you only know <em>existed</em>:</p>
       <p><strong>Set a small bowl of fresh water on a separate cloth</strong> — not on the main altar, but near it, lower if possible. <strong>Place a white candle behind it.</strong> If you have a name, write it on a slip of paper and place it under the bowl. If you do not, write a description: <em>"the great-grandmother whose name was lost." "The brother who died too young." "The ones in the hold of the ship."</em></p>
       <p>Each evening for <strong>nine consecutive nights</strong>, light the candle, pour fresh water, and read aloud one of the seven Psalms of elevation: <em>Psalm 23 (the rod and staff), Psalm 91 (refuge under the wing), Psalm 121 (the lifting of eyes), Psalm 23 again, Psalm 27 (the light and salvation), Psalm 130 (out of the depths), Psalm 51 (cleanse me).</em> If Psalms are not your tradition, speak instead the elder's prayer: <em>"You are remembered. You are loved. You are released from what held you. Rise. Rise. Rise. The road is open. Your people are waiting on the other side."</em></p>
       <p>On the ninth night, after the prayer, <strong>say goodbye</strong>. Pour the bowl out onto the earth. Snuff the candle. Burn the slip of paper if it is safe to do so, and bury the ash. <em>The working is complete. The soul has risen.</em> You may notice — many practitioners do — a sudden lightness in the home. A particular tension you did not know you were carrying releases. <strong>That is the soul rising. That is also you, no longer carrying it.</strong></p>`,

      `<h3>The Reliquary — When You Do Not Know the Grave</h3>
       <p class="no-indent">For students who do not know where their oldest ancestors are buried, the elders developed a beautiful technological substitute. It is called by various names — the <em>Bwiti reliquary</em> (in the Gabonese tradition, where it originates), the <em>Blackhawk-in-the-Bucket</em> (in the New Orleans Spiritualist tradition, where it adapted), the <em>ancestor bucket</em> in many African American conjure houses. The principle is the same: <strong>build a vessel that can host the soul, fill it with conducive matter, and tend it daily until the soul recognizes it as home.</strong></p>
       <p>The basic form: a <strong>bucket or large bowl</strong>, opaque if possible. Inside, place: dirt from a <em>crossroads</em> (where roads meet, intentions cross, spirits gather), dirt from a <em>cemetery</em> (any cemetery, ideally one in your area, taken with proper payment as in lesson three), and one item of <em>personal connection</em> — a sculpted head, a small statue, a photograph in a sealed bag, a written name on parchment. <em>This is the reliquary.</em></p>
       <p>Place the reliquary on or beside the altar. Tend it daily — light the candle near it, speak the names you wish to draw, pour libation onto the dirt inside. Over the course of approximately <strong>one year</strong>, the soul will move into the vessel. You will know it has — there is a marked shift in the room, in your dreams, in the responsiveness of the working. <em>The reliquary becomes the place where your unmarked dead live.</em> It is the diaspora's answer to the lost grave.</p>`,

      `<h3>What Tending Actually Feels Like</h3>
       <p class="no-indent">Most members report, after their first weeks of consistent altar tending, the same handful of experiences. A <strong>warmth</strong> in the chest when they pass the altar. A surprising <strong>vivid dream</strong> in the third or fourth night. A <em>knowing</em> arriving when they ask a question — not a voice, but a settled feeling, a "<em>oh, of course</em>." A small <strong>tear</strong>, unexpected, on the seventh day, that they cannot fully explain.</p>
       <p>Almost no one reports fear. The ones who do are usually carrying inherited stories — a Pentecostal grandmother's warning, a half-remembered horror movie, a church sermon from age nine — and the fear softens within two weeks of consistent practice. <strong>The body learns, faster than the mind, that this is not what it was told it would be.</strong></p>
       <h3>If Fear Does Come</h3>
       <p class="no-indent">Acknowledge it. Speak it aloud at the altar: <em>"I am afraid. I was taught to be afraid. I am here anyway. Help me."</em> Then continue tending. Fear is not a sign that you are doing something wrong. <strong>Fear is often the last layer of the slander leaving the body.</strong> Tend through it. The ancestors are patient. They have waited longer than you can imagine.</p>
       <h3>Your Practice This Week</h3>
       <p class="no-indent">Identify <strong>one ancestor in your line who was not properly grieved</strong>. (Most of us can name one without thinking — the uncle who was never spoken of, the great-aunt who died young, the one whose photograph was kept in a drawer.) Begin the nine-night elevation working for them. Keep notes each night of what you feel before, during, and after. By the ninth night, write a short letter to them — and burn it.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#6a3a14;">Final chapter: <em>When They Speak Back</em> — and the thirteen guidelines that make a person worthy of becoming an ancestor in turn.</p>`
    ]
  },

  // ─── LESSON 5 — When They Speak Back & Iwa-pele as Inheritance ─
  { id:'a5', name:'When They Speak Back & Iwa-pele as Inheritance', time:'22 min',
    glyph:'☥', x:'82%', y:'70%',
    prompt:'When have you felt them already? And what kind of ancestor will you become?',
    lead:'They have been speaking the whole time. The work is to slow down enough to hear — and to live in such a way that you, too, become someone worth speaking to.',
    excerpt:'They speak in <strong>dreams</strong>. They speak in the hawk that crosses your path twice in one week. They speak in the song that comes on the radio at the exact moment you needed it. The work of this module ends with two recognitions: that the conversation has been happening all along — and that <strong>you are becoming an ancestor too</strong>. The thirteen guidelines of <em>Iwa-pẹlẹ</em> are the elders\' inheritance to you, and your daily examination of conscience.',
    pages: [
      `<p class="dropcap no-indent">There is a kind of grief peculiar to the modern Black woman that the elders recognize on sight: the grief of having been <strong>spoken to your whole life and never having known how to listen</strong>. The hawks were there. The dreams were there. The smell of cigarettes in a room where no one had smoked for forty years was there. The song that ambushed you in the grocery store the day before the diagnosis — that was there too. The ancestors were never silent. <em>The receiver was tuned to the wrong frequency.</em></p>
       <p>This last lesson of the Ancestral Veneration module is not about <em>calling them in</em>. By now, after four weeks of altar work, they are already coming. The lesson is about <strong>recognizing the signal</strong>. Learning the alphabet they have been writing in for years. Trusting the language of your own life enough to read it. And then — the harder work — <em>becoming someone whose name is worth speaking, when your turn comes</em>.</p>
       <div class="bk-quote">"The ancestors were never silent. The receiver was simply tuned to the wrong frequency."</div>`,

      `<h3>The Five Channels They Use</h3>
       <p class="no-indent">Across Africana traditions — and confirmed in the testimonies of countless practitioners — the ancestors most frequently speak through five channels. Different lineages emphasize different ones, but every practitioner eventually meets all five.</p>
       <p><strong>1. Dreams.</strong> The most universal channel, and the one most explicitly named in the tradition as a <em>two-way conduit</em>. Especially dreams that <em>repeat</em>, dreams in which a deceased person is unusually clear-eyed and articulate, dreams set in houses you have never lived in but somehow know the layout of. The dead use the dream-state because your defenses are down — you cannot intellectualize them away in your sleep. <strong>Dreams are also where they bring warnings of impending danger.</strong> If a deceased person comes to you in a dream and tells you something specific — pay attention. The elders teach: <em>act on it within forty-eight hours, or pour libation and ask for a confirming sign.</em></p>
       <p><strong>2. Animals and Birds.</strong> A particular bird that crosses your path repeatedly. A hawk circling. A black cat that appears on three consecutive evenings. A dragonfly at a funeral. In Yoruba tradition, certain animals are <em>messengers</em> — and the diaspora retained this knowledge even when the names were lost. <em>Pay attention to who keeps showing up.</em></p>`,

      `<p><strong>3. Music and Sudden Sound.</strong> A song the deceased loved, on the radio, at a moment of decision. A wind chime ringing on a still day. A clock that has been broken for years suddenly chiming. The dead are <em>fond of audio</em>. They worked too hard, in life, on the songs they loved, to ever fully let them go.</p>
       <p><strong>4. Numbers, Names, and Coincidence.</strong> A repeated number sequence. A stranger introducing themselves with the deceased's name. The license plate, the receipt total, the apartment number. The Western mind calls this "coincidence." The African mind calls it <em>conversation</em>. <em>Both are valid descriptions of the same event; only one of them is useful.</em></p>
       <p><strong>5. The Body's Sudden Knowing.</strong> A wave of warmth in the chest while folding laundry. Tears that arrive with no precipitating thought. The hair on your arms rising in an empty room. A sentence forming in your mind that does not sound like your own internal voice — it is gentler, older, more patient. <strong>That is them.</strong> The body is the most honest receiver. It has not learned to lie about what it senses.</p>
       <div class="bk-quote">"The Western mind calls it coincidence. The African mind calls it conversation."</div>`,

      `<h3>The Hardest Part — Believing It</h3>
       <p class="no-indent">After they speak, the modern mind does its work. <em>"That was just a coincidence." "That bird was just a bird." "I was probably going to think of her anyway — it's been two years."</em> The dismissal is automatic, well-trained, and often sounds remarkably like a parent or teacher who shamed you, long ago, for believing in invisible things.</p>
       <p>Here is the elder counsel: <strong>when in doubt, choose to believe</strong>. Not because skepticism is wrong. Skepticism is healthy in many domains. But in the domain of ancestral conversation, the cost of disbelief is far higher than the cost of credulity. If you believe a hawk was a message and you were "wrong" — you spent a quiet moment of attention, you sent gratitude across the veil, and nothing was lost. If you believe a hawk was nothing and you were "wrong" — <em>you missed a letter from someone who loved you</em>.</p>
       <p>Choose the more loving error. The ancestors will not punish you for over-listening. They will gently correct you, in time, if you mishear. <strong>The penalty is on the side of dismissal, not on the side of belief.</strong></p>`,

      `<h3>How to Reply</h3>
       <p class="no-indent">When you notice a sign — a dream, a bird, a song — the ancestors are not waiting for you to <em>solve</em> it. They are waiting for you to <strong>acknowledge</strong> it. The reply is small and matters enormously. At the altar, light the candle and say: <em>"I saw the hawk. I heard the song. Thank you. I am listening. Tell me more if there is more."</em></p>
       <p>That is enough. They are not testing you. They are <em>visiting</em> you. The reply is what makes the visit feel <strong>received</strong>, and a received visit invites another. This is how the conversation deepens — not through grand ceremony, but through <em>polite, consistent acknowledgment of the messages already arriving</em>.</p>
       <h3>The Listening Log</h3>
       <p class="no-indent">A practical tool the elders endorse: keep a small notebook beside your bed. Each morning, before you reach for your phone, write down: (1) any dream you remember, even fragments. (2) Any "coincidence" from the previous day that struck you. (3) Any moment your body knew something before your mind did. Do not interpret. Do not analyze. <strong>Just record.</strong> By the seventh morning, read the week back. A pattern will emerge. <em>That is the conversation.</em></p>`,

      `<h3>Iwa-Pẹlẹ — The Inheritance That Makes You an Ancestor</h3>
       <p class="no-indent">We have spoken throughout these lessons of <strong>Iwa-pẹlẹ</strong> — balanced character, the only thing that travels with you across the threshold. Here, at the close of the module, we name what the elders teach explicitly: <em>the Iwa-pẹlẹ you build in your lifetime is what determines whether you become a venerated ancestor in turn</em>. The work is reciprocal. You tend them; they shaped you; you become someone the next generation can tend.</p>
       <p>Across African traditions, the path of Iwa-pẹlẹ has been distilled into <strong>guidelines</strong> — practical, daily disciplines that, if held, build the kind of character that makes a soul rise easily after death and remain available to the lineage. There is no single fixed list, but a synthesis of what the elders most consistently name produces <em>thirteen</em>:</p>`,

      `<h3>The Thirteen Guidelines</h3>
       <p class="no-indent"><strong>1. Do not steal.</strong> Not money, not credit, not another's words, not another's spouse, not another's dignity.</p>
       <p><strong>2. Do not be selfish.</strong> The ancestor was generous. Match.</p>
       <p><strong>3. Respect your elders.</strong> Even the difficult ones. Especially the difficult ones.</p>
       <p><strong>4. Speak honestly.</strong> Lying scrambles the Aṣẹ around you. Truth, even hard truth, builds clean character.</p>
       <p><strong>5. Do not harm the children.</strong> Not yours; not anyone's. The line ahead of you is sacred.</p>
       <p><strong>6. Honor your word.</strong> A promise made is a promise to be kept; a promise broken is a small theft.</p>
       <p><strong>7. Tend the dead.</strong> Pour libation. Light the candle. Say the names. This is how they tend you back.</p>
       <p><strong>8. Cultivate humility.</strong> Olódùmarè is the only one who deserves boasting. You are a small light.</p>
       <p><strong>9. Practice generosity, especially with food.</strong> A plate prepared for someone hungry returns to you sevenfold.</p>
       <p><strong>10. Care for your body.</strong> It is the temple where the work gets done.</p>
       <p><strong>11. Do not curse the innocent.</strong> Words have power. Aim them carefully.</p>
       <p><strong>12. Forgive — slowly, and on your own clock.</strong> Holding grievance is carrying ash that is not yours to carry.</p>
       <p><strong>13. Live in such a way that your name will be spoken with warmth after you go.</strong> This is the final exam.</p>
       <div class="bk-quote">"Live in such a way that your name will be spoken with warmth after you go. This is the final exam."</div>`,

      `<h3>Your Practice This Week — and For the Rest of Your Life</h3>
       <p class="no-indent">At your altar, each evening, after you have lit the candle and poured libation and spoken the names, ask one question of the day: <em>"Of the thirteen — which one did I tend well today? Which one slipped?"</em> Do not flagellate. Do not perform. Just notice. <strong>The ancestors are not punishers. They are coaches. They are watching the same scoreboard you are watching, and they are rooting for you.</strong></p>
       <p>Over weeks, you will notice that one or two of the thirteen are your <em>persistent edge</em> — the place you slip most. <strong>That is your work in this lifetime.</strong> That is the reason you came back. The other twelve will, mostly, take care of themselves. The one or two are your teaching.</p>
       <h3>You Are a Cell in a Larger Body</h3>
       <p class="no-indent">If you take only one thing from this module, take this: <strong>you are not, fundamentally, an isolated individual. You are a cell in a larger ancestral body.</strong> The body is wounded — by enslavement, by colonization, by displacement, by the ten thousand small severings of modern life. The work of altar tending is not piety or hobby. It is <em>medicine for the body</em>. When you tend, the body heals — and you, the cell, find yourself less restless, less afraid, more clearly purposed, more deeply held.</p>
       <p>You will know the work is taking root when you notice, one ordinary afternoon, that you no longer feel <em>alone</em>. Not in a romantic or social sense. In a deeper, structural sense. <em>You are accompanied.</em> The room you walk into is no longer empty. The decision you face is no longer yours alone. <strong>The ancestors are with you. They were always with you. You simply, finally, made them welcome.</strong></p>
       <p class="no-indent" style="margin-top:32px;text-align:center;font-style:italic;color:#6a3a14;">Module II complete. The next module — <em>Orisha & Spirit Systems</em> — meets the divine intelligences who walk with you, and teaches you to map them onto your own body as a living temple.</p>`
    ]
  }

];
