// ══════════════════════════════════════════════════════════════
// MODULE III — ORISHA & SPIRIT SYSTEMS ("The Many Faces of the Divine")
//   Five lessons, each ~8 pages, essay-form voice.
//   Source curriculum:
//     • The One and the Many (Olódùmarè / Orisha as emanations)
//     • The Seven Major Orisha (Obatala, Eshu, Ogun, Oshun, Yemoja, Shango, Oya)
//     • Orisha as internal forces (Orisha-chakra map)
//     • Iwa-pele as the goal of Orisha relationship
//     • Nommo, ancestors as intermediaries, sacred art
// ══════════════════════════════════════════════════════════════
window.MODULE_3_LESSONS = [

  // ─── LESSON 1 — The One and the Many ─────────────────────────
  { id:'o1', name:'The One and the Many', time:'20 min',
    glyph:'☉', x:'50%', y:'30%',
    prompt:'Where in your life do you mistake a part for the whole?',
    lead:'There is one Divinity. The Orisha are its faces. Many in number, single in source.',
    excerpt:'Before we meet any individual Orisha, we must understand the architecture of the system. There is <strong>one Divinity</strong> — Olódùmarè, the Source. The Orisha are <em>emanations</em> of that Source: divine functionaries, district governors of reality, faces the One wears so that finite beings can know the infinite. The pantheon is not polytheism. It is <strong>monotheism with a thousand windows</strong>.',
    pages: [
      `<p class="dropcap no-indent">When the missionaries first encountered our traditions, they saw what they expected to see. <em>Idols. Many gods. Heathenism.</em> They did not pause to ask the elders what was actually being taught. If they had, they would have heard a teaching subtler and older than the monotheism they had brought across the water: <strong>there is one Source, and the Source has many faces</strong>. The faces are not the Source. The Source is not reducible to any single face. Both statements are true at once, and the tradition holds them both without strain.</p>
       <p>The Yoruba have a phrase for this — <em>Ẹnìkan ni Olódùmarè; ọpọ ni àwọn òrìṣà</em>. "Olódùmarè is one; the Orisha are many." It is one of the foundational propositions of the entire system. Lose hold of it, and the tradition becomes either a flat polytheism (which it is not) or a sterile monotheism that cannot speak to the actual textures of human life (which it also is not). Hold both, and a remarkable architecture comes into view.</p>
       <div class="bk-quote">"Olódùmarè is one. The Orisha are many. Both statements are true at once."</div>`,

      `<h3>Why the One Needs Many Faces</h3>
       <p class="no-indent">Olódùmarè — the Supreme Being — is, in classical Yoruba theology, <strong>ineffable</strong>. Beyond gender. Beyond name. Beyond direct relationship. The elders teach that to approach Olódùmarè directly, with prayers about parking spots and rent and the man who broke your heart, would be like writing the President of the country to ask for a stamp. <em>The architecture is too vast.</em> The Source does not require petitioning, because the Source is not a personality. The Source is <strong>the field within which all persons exist</strong>.</p>
       <p>So how does a human being have a relationship with the divine? Through <strong>the Orisha</strong> — divine functionaries, departmental heads, district governors. They are <em>emanations</em> of the One Source: not separate gods, but specific concentrations of the divine attention, each one tuned to a particular aspect of human experience. Obatala for ethical clarity. Oshun for love. Ogun for path-clearing. Yemoja for the womb of the world.</p>
       <p>The Orisha are how Olódùmarè becomes <strong>reachable</strong>. They translate the infinite into the finite. They are the working interface between you and the Source. <em>And like any good interface, they have specific protocols, and they answer to specific calls.</em></p>`,

      `<h3>Are They Real?</h3>
       <p class="no-indent">This is the question every modern student asks within the first week, and it is the right question. Are the Orisha <em>actual beings</em>, with consciousness and agency? Or are they <em>archetypes</em> — psychological patterns dressed up as personalities? Or are they <em>natural forces</em> — the river itself becoming Oshun, the iron itself becoming Ogun?</p>
       <p>The elders' answer is unsettling to the Western mind because it refuses to choose. <strong>All three are true simultaneously.</strong> The Orisha are real beings with agency. They are also archetypal currents within the human psyche. They are also the very forces of nature you can see and touch. <em>The river is Oshun. The river is also a metaphor for Oshun. Oshun is also a being who can hear you when you speak to her at the river.</em> The tradition holds all three positions at once and finds no contradiction.</p>
       <p>This is what makes the Orisha system so durable across centuries. A scientist can treat them as natural forces. A psychologist can treat them as archetypes. A devotee can treat them as persons. <strong>All three approaches yield real results, because all three are true.</strong> The system is not asking you to abandon your rational mind. It is asking you to expand it.</p>
       <div class="bk-quote">"The river is Oshun. The river is also a metaphor for Oshun. Oshun is also a being who can hear you when you speak."</div>`,

      `<h3>Spirit Beings First</h3>
       <p class="no-indent">There is a teaching the elders return to whenever a student begins to drift toward "spiritual practice as separate from ordinary life." <strong>You are a spirit being having a human experience. There is no part of your life that is not spiritual.</strong> The walk from the bus stop is spiritual. Folding the laundry is spiritual. The hard conversation you are avoiding is spiritual. The Orisha are not <em>visited</em> on Sundays. They are present, continuously, in the rhythms of every ordinary act.</p>
       <p>This is one of the great gifts of African spiritual thinking to the modern fragmented self: <em>everything is spirit, in different states of vibration</em>. The chair is spirit. The cup is spirit. Your impatience is spirit. Your love for your child is spirit. There is no secular zone, no profane corner, no place where the divine has agreed not to look. The work is not to <em>add</em> spirituality to a non-spiritual life. The work is to <strong>recognize</strong> the spiritual nature of the life you already have.</p>
       <p>When you understand this, the Orisha stop seeming like distant deities to whom you must travel. They are the very textures of your day. <em>Ogun is the iron of your kitchen knife. Oshun is the honey in your tea. Yemoja is the water from your tap.</em> The system is not asking you to leave your life and go elsewhere to find them. It is teaching you to recognize them where they have always been.</p>`,

      `<h3>Pantheon as Map of Consciousness</h3>
       <p class="no-indent">A useful way to hold the seven (or sixteen, or four hundred and one — depending on the count) Orisha is as a <strong>map of human experience</strong>. Each Orisha presides over a domain of life that every human being must, at some point, navigate. Love. Work. Justice. Grief. Fierce protection. Tender nurture. Sudden change. Stubborn endurance. The Orisha are the <em>names we give to the modes of being human</em> — not external to us, but specific concentrations of divine intelligence that, when invoked, can teach us how to walk that particular terrain well.</p>
       <p>This is why no single Orisha is "your god" the way a Christian might say "my Lord." The tradition is not henotheistic. <strong>You will need all of them at some point in your life</strong>, because you will face all the terrains they govern. The relationship a person has with one Orisha as their <em>head Orisha</em> (the Olori — we will meet this in lesson five) is not exclusive worship. It is recognition that one current runs particularly strongly through your own being. The others remain available, and their full deployment is part of building a complete life.</p>`,

      `<h3>Seven Major Faces (Brief Roll Call)</h3>
       <p class="no-indent">Across the next three lessons, we will sit with each of the seven major Orisha individually. Here, briefly, is the roll call so you can begin to feel the shape of the pantheon:</p>
       <p><strong>Obatala</strong> — the arch-divinity, sculptor of human form, ethical pillar, prime emissary of Olódùmarè on earth. The white cloth. The mountain. Clarity itself.</p>
       <p><strong>Eshu-Elegba</strong> — the holder of Aṣẹ, the messenger, the gatekeeper of the crossroads. The one who tries the souls of humans to ensure their growth.</p>
       <p><strong>Ogun</strong> — divinity of iron, war, technology, divine justice. The pathmaker. The one who clears.</p>
       <p><strong>Oshun</strong> — the diplomat. Orisha of unconditional love, sensuality, fine arts, fresh water. The cool river.</p>
       <p><strong>Yemoja</strong> — mother of the orisha, divinity of the ocean, of family stability, of the amniotic fluid of the cosmic womb.</p>
       <p><strong>Shango</strong> — the deified king, divinity of lightning, retributive justice, the drum. The transformer who turns base substance into precious.</p>
       <p><strong>Oya</strong> — guardian of the cemetery, divinity of storms, hurricanes, fierce winds of change. The one who tears down so that the new can rise.</p>
       <p>That is the basic chart. Each face will become deeper as we visit them in turn.</p>`,

      `<h3>Ancestors and Orisha — A Crucial Distinction</h3>
       <p class="no-indent">Now that we are entering the territory of spirit systems, we must hold a distinction the elders are clear about: <strong>ancestors are not Orisha</strong>. They are different categories of being. The ancestor — even the most elevated one — was once a human person, and remains in relationship to a specific lineage. The Orisha are <em>not</em> deceased humans. They are emanations of Olódùmarè, present at the world's making, available to all who call.</p>
       <p>That said, the categories work together intimately. In nearly every Africana tradition, the teaching is the same: <strong>wise ancestors often function as the most accessible intermediaries between humans and the higher Orisha</strong>. Your great-grandmother, fully elevated, can speak to Yemoja on your behalf in ways the unelevated soul cannot. The elder who served Ogun in life can introduce you to Ogun in death. <em>The ancestor altar and the Orisha shrine are not in competition. They are different floors of the same building, and the elevator runs both ways.</em></p>
       <p>This is why we did the ancestor work first, in Module II, before opening this module. <strong>You need a working ancestral altar before you begin building Orisha shrines.</strong> The ancestors are the introduction service. Without them, you are knocking on doors no one has prepared the household to open.</p>
       <div class="bk-quote">"Ancestors and Orisha are different floors of the same building. The elevator runs both ways."</div>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Before any Orisha can be approached, the student must build <strong>recognition</strong>. Not worship yet — that is too soon. Just recognition. For seven days, choose <em>one</em> ordinary domain of your life, and ask each evening at your altar: <em>"Which face of the One presides here?"</em></p>
       <p>If you spent the day in conflict, ask: <em>was that Oya, asking me to let something die? Or Shango, asking me to find my voice? Or Ogun, asking me to clear an old path?</em></p>
       <p>If you spent the day in love, ask: <em>was that Oshun in her sweetness, or Yemoja in her holding, or Obatala in his patient seeing?</em></p>
       <p>You will not get the answer right at first. <strong>That is fine.</strong> You are not being tested. You are learning the alphabet. By the seventh evening, you will start to feel which currents are flowing through which moments — and the seven Orisha will stop being a flat list of names and begin to be <em>recognizable presences</em> in the rhythm of your actual days.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#5a3a14;">Next chapter: <em>Eshu and the Crossroads</em> — and why no working begins without first feeding the gatekeeper.</p>`
    ]
  },

  // ─── LESSON 2 — Eshu, Obatala & The Pathmakers ───────────────
  { id:'o2', name:'Eshu, Obatala & The Pathmakers', time:'24 min',
    glyph:'⚹', x:'25%', y:'52%',
    prompt:'Which path in your life is blocked, and who is the right Orisha to call?',
    lead:'Eshu opens the road. Obatala steadies the head. Ogun cuts the bush. Three pathmakers — the architecture of every successful working.',
    excerpt:'Before any working begins, the road must be opened. <strong>Eshu</strong> — gatekeeper, holder of Aṣẹ, trickster who tries souls — is the first to be greeted in every traditional rite. Then comes <strong>Obatala</strong>, the sculptor of human form, the white-cloth ethical pillar. And <strong>Ogun</strong>, the iron-edged path-cutter. Together they form the architecture of right beginnings.',
    pages: [
      `<p class="dropcap no-indent">If you take only one piece of liturgical etiquette from this entire module, take this: <strong>Eshu eats first</strong>. Always. In every working. In every rite. Across every house — Yoruba, Lucumí, Candomblé, Trinidad Orisha, the Hoodoo houses that quietly retained the protocol — the order is the same. Before any other spirit is fed, before any other prayer is offered, before any other Orisha is greeted, <em>Eshu receives the first portion</em>. To skip this step is to attempt to enter a building without first knocking on the door, and the building is justified in not letting you in.</p>
       <p>This is not because Eshu is jealous, or because the system is rigid. It is because Eshu is the <strong>gatekeeper of the crossroads</strong> — the divine functionary who opens or closes the way between worlds. Every prayer you offer to any other spirit must pass <em>through</em> Eshu's territory to reach its destination. He is the postman. He is the door. If the postman has not been greeted, your letter does not get delivered. <em>It is a practical matter, not a moral one.</em></p>
       <div class="bk-quote">"Eshu eats first. Always. He is the door. He is the postman. Greet him, and the road opens."</div>`,

      `<h3>Eshu — Holder of Aṣẹ</h3>
       <p class="no-indent">Eshu (also called Eshu-Elegba, Elegua, Exu, Legba — the names shift across the diaspora; the function holds) is the divine functionary who holds the activating life-force itself. Remember Aṣẹ from Module I — the inherent power that makes manifestation possible? Eshu is the one who <strong>distributes</strong> it. He decides which prayers carry weight, which sacrifices reach their target, which intentions actually <em>move</em> in the world. Without Eshu's cooperation, the most beautiful prayer is just sound vibrating in a room.</p>
       <p>This makes him, paradoxically, the most powerful and the most easily offended of the major Orisha. He is also famously <strong>tricky</strong>. The myths are full of stories where Eshu wears a hat that is white on one side and red on the other, walks down the road between two friends, and produces an argument that destroys their friendship — not because he is malicious, but because he is <em>testing whether they were paying attention to the whole picture or only to their own perspective</em>. To work with Eshu is to be willing to be tested. He does not punish; he <strong>tries souls</strong>. The trial is the gift.</p>
       <p>Eshu's color is red and black. His number is three. His day is Monday. His domains are crossroads, doorways, marketplaces, the boundary between any two states. <em>He lives at every threshold</em> — which is why the African spiritual tradition treats every doorway, including the one to your home, as a place where Eshu's offering should be made.</p>`,

      `<h3>How to Greet Eshu</h3>
       <p class="no-indent">In a fully built Orisha household, Eshu has his own shrine — typically a clay or stone head placed in a small terra-cotta vessel, kept just inside the main doorway, fed weekly with palm oil, smoke, and small offerings. For a student at the beginning of the path, the practice is simpler.</p>
       <p>Each time you begin a working — a prayer, a libation, a candle-lighting at the ancestor altar — pause first and speak: <em>"Eshu, opener of the road. Eshu, holder of Aṣẹ. I greet you first. Carry my words where they need to go. Open the way."</em> That is enough. The greeting can be three breaths. It does not require an elaborate offering. <strong>Eshu requires acknowledgment, not ceremony.</strong></p>
       <p>Once a week — choose a Monday — pour a small libation specifically for Eshu, separate from the ancestor offering. A capful of cane liquor (rum, gin, or whiskey) onto the earth just outside your front door, with the words: <em>"This is for Eshu. Keep my crossroads clean. Keep my road open. Try me only with the trials I can grow from."</em> Then go about your week.</p>`,

      `<h3>The Crossroads Working</h3>
       <p class="no-indent">When a major decision is upon you — a job, a move, the end or beginning of a relationship, any threshold where the road forks — the elders teach a specific Eshu working that has come down through every diaspora tradition: <strong>the crossroads offering</strong>.</p>
       <p>Find a literal crossroads — where two roads cross at right angles. (Any size — a residential intersection works fine.) At dusk, bring three coins (any denomination — pennies are traditional), a small bottle of cane liquor, and a single candle (red, black, or white). Stand at the center of the crossroads if you can, or at the corner if traffic forbids. Light the candle. Pour a small libation in each of the four directions, beginning east. At each pour, name one of the possible paths your decision could take — <em>"This way leads to X. This way leads to Y. This way to Z. And this way is for the path I cannot yet see."</em> Place the three coins at the center.</p>
       <p>Then say: <em>"Eshu, you who know all roads — show me which one is mine. Send me a sign within three days. I am listening."</em> Walk away without looking back. Eshu will answer — usually within three days, often dramatically. <strong>A coincidence that is not a coincidence. A door closing. A door opening. A stranger saying the exact thing you needed to hear.</strong> Pay attention, and follow the sign.</p>`,

      `<h3>Obatala — The Ethical Pillar</h3>
       <p class="no-indent">If Eshu is the door, <strong>Obatala</strong> is the architect who designed the house. He is the arch-divinity — the eldest of the Orisha, the one Olódùmarè entrusted with the sculpting of human form from clay. Every human being who has ever drawn breath was, in the mythic teaching, <em>shaped by Obatala's hands</em>. He is the maker of bodies and the upholder of the ethical structure that makes human life livable.</p>
       <p>Obatala's color is <strong>white</strong> — the color of the cloth on your ancestor altar, the color of priesthood, the color of moral clarity. His domain is <em>cool ethical purity</em>: the steady, non-reactive, wise mind that can hold complexity without panicking and respond from principle rather than impulse. When you have been in conflict and have managed not to say the cruel thing, that was Obatala. When you have held your tongue and waited a day before answering an angry email, that was Obatala. <em>The Obatala in you is the part that does not need to win.</em></p>
       <p>His symbol is the <strong>mountain</strong> — immovable, ancient, weathering everything below without flinching. His dwelling, in the body, is the head — and most particularly the crown, where the Ori (which we will meet again in lesson four) makes contact with Olódùmarè directly.</p>
       <div class="bk-quote">"The Obatala in you is the part that does not need to win."</div>`,

      `<h3>Working With Obatala</h3>
       <p class="no-indent">Obatala is approached when you need <strong>clarity</strong> — when the noise of competing voices has grown so loud that you cannot hear your own true thinking. He is approached when you need <em>moral footing</em> — when a hard ethical question is in front of you and you are tempted to shortcut. He is approached for healing of the head: chronic anxiety, racing thoughts, decision paralysis, the inability to settle.</p>
       <p>His offerings are <strong>cooling and white</strong>: white flowers, coconut, white candles, milk, fresh water, white rice, white kola nut. Never red. Never alcohol (Obatala is one of the few Orisha who is sworn to coolness — alcohol disturbs his current). Approach him in white clothing if you can; failing that, with a clean white cloth on your altar.</p>
       <p>The traditional Obatala prayer is brief and devastating: <em>"Father of the calm head, sculptor of my form — return me to clarity. Cool the fire that is not mine. Let me see plainly what is in front of me. Let me act from principle, not from heat."</em> Recite this in front of a single white candle for nine evenings, and the noise will subside. The decision will become visible. <em>This is Obatala's specific gift: not the answer, but the quiet that allows the answer to be heard.</em></p>`,

      `<h3>Ogun — The Path-Cutter</h3>
       <p class="no-indent">Where Eshu opens the road and Obatala designs the house, <strong>Ogun</strong> is the one who actually <em>builds</em>. He is the divinity of iron, of tools, of the mechanical, of war when war is necessary. In the deep myths, when the Orisha first descended from Ọrun to bring civilization to humans, the bush was thick and impassable. The other Orisha hesitated. <em>Ogun took up his iron machete and cut the road through which all the others walked.</em> Without Ogun, no civilization exists.</p>
       <p>This is what Ogun governs in your life: <strong>the work that has to be done with your hands</strong>. The job site. The gym. The kitchen knife. The car. The repair. The deadline that requires brute discipline rather than inspiration. Ogun is the patron of every trade that uses iron or steel — surgeons, butchers, mechanics, soldiers, blacksmiths, farmers, carpenters. He is the lord of <em>making the path passable for others</em>.</p>
       <p>His color is <strong>green and black</strong> (sometimes red). His day is Tuesday. His symbol is the iron implement — knife, machete, hammer, key. His offerings: yam, palm wine, smoked fish, dog (in the old houses; substitutes are accepted). He is approached when you need <em>strength to do hard work, courage in conflict, or the energy to clear a path that others have failed to clear</em>.</p>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Three small practices for three pathmakers:</p>
       <p><strong>Monday — Greet Eshu.</strong> Pour a capful of any cane liquor onto the earth just outside your front door. Speak: <em>"Eshu, keep my crossroads clean. Keep my road open."</em> One minute. Do it before the work week begins.</p>
       <p><strong>One evening this week — Sit with Obatala.</strong> Light one white candle on a clean white cloth. No alcohol, no incense. Sit for three minutes in deliberate silence. Speak: <em>"Cool my head. Return me to clarity."</em> Notice what happens to the noise.</p>
       <p><strong>One morning this week — Call Ogun.</strong> Before a task that has been hard for you to begin (a project, a workout, a difficult email), place an iron implement nearby — a kitchen knife on the desk, a wrench on the gym bag. Speak: <em>"Ogun, lend me your edge. Let me cut through what is dull in me. Let the path open under my hand."</em> Then begin.</p>
       <p>By the end of the week you will have met three of the seven major Orisha as <strong>actual presences in your day</strong>, not flat names on a page.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#5a3a14;">Next chapter: <em>Oshun, Yemoja & the Mothers</em> — the rivers, the ocean, the diplomatic and the holding.</p>`
    ]
  },

  // ─── LESSON 3 — Oshun, Yemoja & The Mothers ─────────────────
  { id:'o3', name:'Oshun, Yemoja & The Mothers', time:'24 min',
    glyph:'☽', x:'70%', y:'48%',
    prompt:'Where in your life have you confused fierce with hard, or sweet with weak?',
    lead:'Oshun is the river. Yemoja is the ocean. They are not the same body of water — and learning to tell them apart is half of learning to be held.',
    excerpt:'<strong>Oshun</strong> is the diplomat — orisha of fresh water, unconditional love, sensuality, fine arts. <strong>Yemoja</strong> is the matriarch — orisha of the ocean, of family, of the amniotic fluid of the cosmic womb. Together they form the great pair of feminine waters in the tradition. Today we sit with both, and we untangle the difference between <em>sweetness</em> and <em>holding</em>.',
    pages: [
      `<p class="dropcap no-indent">There is a tendency in the modern Western imagination — and increasingly in the new-age renderings of African spirituality — to flatten the divine feminine into a single archetype. The Mother. The Goddess. As if she were one thing, and as if naming her in the singular were the more sophisticated move. The traditional African house is precise where the new-age cannot afford to be: <strong>there is more than one mother</strong>. The waters are not the same waters. The river does not do what the ocean does. The well does not do what the rain does. <em>Each mother has her own work, and the work is non-interchangeable.</em></p>
       <p>This precision is not pedantry. It is <strong>practical</strong>. When you bring a heartbreak to Oshun, expecting Yemoja's holding, you will leave the river still aching. When you bring a question of family lineage to Oshun, expecting her to do the work that belongs to Yemoja, you will get sweetness without depth. The mothers are not a committee. They are <em>specific functionaries</em>, and learning to tell them apart is learning to be helped accurately.</p>`,

      `<h3>Oshun — The Diplomat of Sweetness</h3>
       <p class="no-indent"><strong>Oshun</strong> (sometimes spelled Ọṣun, Ochún, Oxum across the diaspora) is the orisha of <strong>fresh water</strong> — the river specifically, not the ocean. She is the great diplomat of the pantheon. There is a foundational myth in Yoruba tradition in which the male Orisha gathered to set the world in order, did not invite the female Orisha to their council, and watched as everything they tried to build fell apart. They could not figure out why. Eshu told them: <em>"You did not invite Oshun. Nothing on earth will work until she is at the table."</em> They invited her. The world began to function.</p>
       <p>This is the central teaching about Oshun: <strong>without her, the work does not flow</strong>. She is the lubricant of cooperation, the coolness of fresh water, the diplomatic intelligence that makes hard parties able to come to the table. Where Ogun cuts and Shango thunders, Oshun <em>persuades</em>. She is the warmth that makes the system work. She is also, and this is critical, <strong>fierce</strong>. The same myth ends with Oshun, now invited, demonstrating that her cooperation is conditional — and her withdrawal is catastrophic. <em>Sweetness is not weakness. Sweetness is power that has chosen restraint.</em></p>
       <div class="bk-quote">"Sweetness is not weakness. Sweetness is power that has chosen restraint."</div>
       <p>Oshun's color is <strong>yellow and gold</strong>. Her metal is brass. Her number is five. Her day is Saturday. Her symbol is the brass fan, the mirror, the river. Her offerings: <em>honey</em> (always tasted by the priestess first, to confirm it has not been poisoned — there is a myth here we will return to), oranges, sunflowers, cinnamon, white wine, pumpkins, brass jewelry. She accepts these in fives or multiples of five.</p>`,

      `<h3>Working With Oshun</h3>
       <p class="no-indent">Oshun is approached for: <strong>love</strong> (not romance only — all love, including self-love), <strong>diplomacy</strong> (when a relationship has hardened and you need it to flow again), <strong>fertility</strong> (of the body, of creative work, of any project that wants to bear fruit), <strong>art</strong> (Oshun is the patron of every form of beauty-making), and <strong>money</strong> (specifically the money that comes from being valued, from being seen, from your gifts being received).</p>
       <p>The traditional Oshun working is performed at a <strong>river</strong> if possible — any flowing body of fresh water. Bring honey, an orange, a yellow flower, and five coins. Stand at the bank. Anoint your wrists, throat, and the inside of your elbows with honey (warm; fingertips). Speak to Oshun about what you have come for: <em>"Oshun, river-mother, you who cool the fevered head and sweeten the bitter heart — I have come to ask for [name your need]. Let it flow. Let me be received."</em> Place the orange and the flower at the river's edge. Throw the five coins into the moving water. Walk away without looking back, as you did with Eshu.</p>
       <p>If no river is reachable, fill a clean glass bowl with cool water, add a teaspoon of honey, place five coins at the bottom, and float a yellow flower on the surface. Set this on your altar. The principle is the same: <strong>moving sweetness, openly offered</strong>.</p>`,

      `<h3>The Honey Test</h3>
       <p class="no-indent">A protocol the elders insist on, and one that has saved many practitioners from harm: <strong>before offering honey to Oshun, you must taste it yourself</strong>. The story behind this — the brief version — is that an enemy once tried to poison Oshun by offering her tainted honey. After that, she required that all honey offered to her be tasted by the offerer first, in front of her. To this day, in every traditional house, before honey is placed on Oshun's altar or used in any working in her name, the practitioner takes a small dab on the fingertip and tastes it openly.</p>
       <p>This is more than a ritual quirk. It is a <strong>teaching about integrity</strong>. <em>Do not offer to the divine what you would not put in your own mouth.</em> Whatever you bring to the altar — honey, words, intention, work — you should be willing to consume yourself. The honey test is a small daily reminder: <strong>the offering is a mirror. Bring what is true.</strong></p>`,

      `<h3>Yemoja — The Matriarch of the Ocean</h3>
       <p class="no-indent">If Oshun is the river, <strong>Yemoja</strong> (Yemayá, Iemanjá, Yemowo across the diaspora) is the <strong>ocean</strong> — and the difference is enormous. Where Oshun is sweet, Yemoja is <em>vast</em>. Where Oshun is the diplomat, Yemoja is the <em>matriarch</em>. Where Oshun is the warmth that lubricates, Yemoja is the <em>amniotic fluid in which the entire cosmos floats</em>. She is the mother of the orisha themselves — many of the great Orisha, in different versions of the tradition, are her children. She is the womb of the world.</p>
       <p>Her domains are: <strong>family stability</strong>, the <em>foundation</em> beneath relationships, <strong>maternal protection</strong> (especially of children), the <em>deep currents of the unconscious</em>, the wombs of women, the moon's pull on tides, the mysteries of the deep. She is the orisha to approach when you need to feel <strong>held</strong> — not advised, not energized, not motivated. <em>Held</em>.</p>
       <p>Her color is <strong>blue and white</strong> — the colors of the sea, of mother-of-pearl, of moonlit water. Her metal is silver. Her number is seven. Her day is Saturday (shared with Oshun, mother and daughter). Her symbols are the seashell, the silver crescent moon, the fan made of peacock feathers. Her offerings: <em>watermelon</em>, molasses, blue grapes, white candles, silver coins, blue cloth, seashells. Always presented in sevens.</p>`,

      `<h3>The Difference, Practically</h3>
       <p class="no-indent">If you have lost something — a relationship, a confidence, a sense of belonging — and you need to be <strong>held while you grieve</strong>, you go to Yemoja. If you have lost something and you need to be <strong>sweetened back into hope</strong> so you can re-enter life, you go to Oshun. Both are appropriate. The order, often, is Yemoja first (let the grief be held in the deep waters), then Oshun (let the warmth return).</p>
       <p>If you are about to bring a child into the world, or already have, Yemoja is the orisha who watches over the child's earliest years. She is the protector of pregnancy, of nursing, of the quiet years before language. Oshun is also a mother (her own myths include divine motherhood), but Oshun's mothering is the <em>delight</em> of the child — the laughter, the discovery, the sweetness. Yemoja's mothering is the <em>floor</em> the child stands on. Both are required.</p>
       <p>If you are doing genealogy work — recovering names, finding lost branches of the family, healing intergenerational wounds — Yemoja is your orisha. The depths know what the surface has forgotten. <em>The ocean has been everywhere your ancestors went.</em></p>`,

      `<h3>The Yemoja Working — At the Sea</h3>
       <p class="no-indent">If you can reach the ocean, the working is simple and ancient. Bring seven white flowers (white roses are traditional), a small bottle of molasses, a piece of fruit (watermelon if it is in season; otherwise white grapes or a coconut), and seven silver coins. Stand at the water's edge at <strong>dusk or dawn</strong>, when the boundary between the elements is most permeable. Place the offerings on a small flat stone or piece of driftwood. Speak: <em>"Yemoja, mother of the orisha, womb of the world, holder of all who have been lost — I bring you this. I come to ask to be held. Let me feel your weight beneath me."</em></p>
       <p>Then — and this is the part that surprises modern students — <strong>let the tide take it</strong>. Do not place the offerings beyond the tide line; place them <em>where the next wave will reach them</em>. If the ocean accepts (most often, the tide will rise and pull them in), you have been received. If the ocean refuses (the offerings remain on dry sand for an hour), come back another day and bring something different. Yemoja has her preferences.</p>
       <p>If no ocean is reachable, fill the deepest vessel you have with cold water, add a tablespoon of sea salt, place seven coins at the bottom, float seven white petals on the surface. Set on the altar with a single blue candle. The principle is the same: <strong>the deep, holding water, accepting your weight</strong>.</p>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Choose <em>one</em> of the two mothers. Whichever you feel pulled toward, or — better — whichever you have been <em>resisting</em>. (The orisha you resist is often the one you most need.)</p>
       <p>If <strong>Oshun</strong> — set up a small Oshun corner: a yellow cloth, a small dish with a teaspoon of honey (taste it first), an orange, a yellow flower (real or fabric), five coins. Each evening for seven days, anoint your wrists with cool water and a fingertip of honey. Speak briefly to Oshun about one thing in your life that needs to flow more sweetly. Notice what shifts in how you are received by others.</p>
       <p>If <strong>Yemoja</strong> — set up a small Yemoja corner: a blue cloth, a deep bowl of cool salted water, seven white petals floating on top, seven silver coins at the bottom, one blue candle. Each evening for seven days, light the candle, place your hands palms-down on either side of the bowl, and ask to be held. Notice what surfaces from the depths — a memory, a longing, a name you had forgotten.</p>
       <p>By the end of the week, you will have begun a relationship with one of the great mothers. The other is patient. She will be there when you are ready.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#5a3a14;">Next chapter: <em>Shango, Oya & the Storm</em> — fire, lightning, and the holy work of tearing things down.</p>`
    ]
  },

  // ─── LESSON 4 — Shango, Oya & The Storm ────────────────────
  { id:'o4', name:'Shango, Oya & The Storm', time:'22 min',
    glyph:'⚡', x:'30%', y:'78%',
    prompt:'What in your life is being torn down right now — and is it being torn down by you, or for you?',
    lead:'Shango is the lightning. Oya is the wind that arrives just before it. Together they are the holy storm — and not every storm is a punishment.',
    excerpt:'<strong>Shango</strong> — the deified king, divinity of lightning, retributive justice, and the drum. <strong>Oya</strong> — the orisha of storms, hurricanes, the cemetery, and sudden change. Together they teach the most uncomfortable truth in the tradition: <em>some things must be torn down so that the new can rise</em>. And the tearing-down, when it comes from these two, is not punishment. It is <strong>liberation</strong>.',
    pages: [
      `<p class="dropcap no-indent">If Module III has a turning point, this is it. Up until now, the orisha we have met have been broadly welcoming. Eshu opens roads. Obatala steadies the head. Ogun cuts a path. Oshun sweetens. Yemoja holds. The student approaches them and feels — appropriately — that the divine is on their side. Then we arrive at <strong>Shango and Oya</strong>, and the tone changes. These two orisha are not gentle. They are <em>not unkind</em>, but they are not gentle. They are the storm.</p>
       <p>And here is where many modern students hesitate. <em>Why would I want a relationship with the storm?</em> The answer the elders give is unsettling and exact: <strong>because the storm is already in your life</strong>. The job ending. The relationship that imploded. The inherited family pattern that finally cracked. The sudden, unwelcome clarity. These are not random misfortunes. They are <em>weather</em>, and the orisha of weather have specific names. To ignore the storm is not to escape it. To acknowledge it is to find that <strong>the storm has a face, and the face is not your enemy</strong>.</p>
       <div class="bk-quote">"To acknowledge the storm is to find that the storm has a face — and the face is not your enemy."</div>`,

      `<h3>Shango — The Deified King</h3>
       <p class="no-indent"><strong>Shango</strong> (Sàngó, Changó, Xangô) is unique among the seven major orisha in one important sense: <em>he was once human</em>. He was the fourth Alaafin (king) of the Old Oyo Empire, sometime around the 14th century. He ruled with thunderous force, made enormous expansions of the empire, and ended his reign in disputed circumstances. After his death, his court declared him deified — risen to the rank of orisha — and his cult spread from Oyo across all of Yorubaland, then across the Atlantic. <em>He is the bridge between the ancestor world and the orisha world</em>: a human soul elevated so completely that he became one of the divine functionaries. His worship, therefore, has a particular texture. He understands what it is to be human. <strong>He has done the marketplace.</strong></p>
       <p>Shango's domain is <strong>lightning, fire, the drum, masculine virility, retributive justice, and the kingly arts</strong>. He is the orisha to call when a wrong has been done to you and you need <em>righteous fire</em>. He is the patron of those who use the voice with power — orators, leaders, performers, those whose work requires presence. He is the patron of the <em>bata drum</em> — the three-headed sacred drum whose rhythms are said to be Shango's voice itself.</p>
       <p>His colors are <strong>red and white</strong>. His metal is none — Shango's element is fire, not iron. His number is six. His day is Wednesday or Friday (varies by tradition). His symbols are the <em>double-headed axe</em> (oshe Shango), the bata drum, lightning, the ram. His offerings: <em>amala</em> (a yam-flour porridge), red apples, plantains, red wine, smoked goat, kola nut. Always in sixes.</p>`,

      `<h3>Shango's Lightning — The Transformer</h3>
       <p class="no-indent">A specific teaching about Shango that the elders return to: <strong>lightning is a transformer</strong>. When lightning strikes a tree, the tree is not just destroyed — it is <em>changed at the molecular level</em>. The wood becomes different wood. The soil where it landed becomes different soil. Lightning is the elemental force that takes <em>base substance and makes it precious</em>. It is, in a literal sense, an alchemist.</p>
       <p>This is what Shango does in your life when he is invited. He does not just clear obstacles (that is Ogun's work). <strong>He transforms what was lying around as base material into something refined.</strong> An old grief becomes the foundation of a creative work. A failed career becomes the unexpected ground of a true vocation. A wound becomes the site of your most powerful teaching to others. Shango is the orisha of the <em>conversion experience</em> — the moment when what looked like destruction reveals itself, retrospectively, as <em>elevation</em>.</p>
       <p>Approach Shango when you are angry and need the anger to do useful work, when an injustice needs to be addressed and ordinary diplomacy has failed, when you need to step into a public role and find your kingly voice, when the base material of your life feels ready to be transformed. The traditional invocation is brief: <em>"Shango, who walks with thunder, king of the lightning road — strike where I cannot strike. Refine what I cannot refine. Let the fire that visits me be a fire that elevates."</em></p>`,

      `<h3>Oya — The Wind That Arrives Just Before</h3>
       <p class="no-indent">If Shango is the lightning, <strong>Oya</strong> is the <em>wind that arrives just before</em>. She is the orisha of <strong>sudden change, storms, hurricanes, tornadoes, the cemetery, and the marketplace</strong>. She is also, in the deep myths, Shango's most important wife — the only orisha who can match his fire and walk beside it without being consumed. The two of them together form the great elemental pair: the wind that announces the lightning, the lightning that follows the wind.</p>
       <p>Oya's specific work in human life is <strong>the tearing-down that makes new beginnings possible</strong>. She is the orisha of <em>endings that are necessary</em>. The job that had to be lost. The relationship that had to fall apart. The version of the self that had to die so the next version could be born. She is also the guardian of the <em>cemetery</em> — not because she is morbid, but because she presides over the threshold between this life and the next, and she is the one who escorts souls across.</p>
       <p>Her colors are <strong>maroon, deep purple, and rainbow</strong> (the nine-colored cloth of the storm). Her metal is copper. Her number is nine. Her day is Wednesday. Her symbols are the <em>iruke</em> (a horsetail flywhisk), the buffalo horn, lightning that arcs sideways, the rainbow. Her offerings: <em>eggplant</em>, plums, red wine (matching Shango), roots, rainbow-cloth, copper coins. In nines.</p>`,

      `<h3>Oya in the Marketplace</h3>
       <p class="no-indent">A detail about Oya that the elders insist on, which surprises modern students: <strong>she is the orisha of the marketplace</strong>. Not just storms and cemeteries — also the marketplace, where everyone gathers, where transactions happen, where information is exchanged. <em>Why?</em> Because the marketplace, like the storm, is a place of <em>rapid change</em>. Prices shift. Fortunes turn. News arrives. The marketplace is where the wind of the world picks up and redistributes things. Oya is its presiding spirit.</p>
       <p>This means: when you are in a moment of life where everything is in flux — career change, geographic move, the sudden loss of an established arrangement — you are in <em>Oya's territory</em>. The wind has picked up around you. The marketplace of your life is being reshuffled. <strong>Resisting the wind is not the answer. Recognizing whose wind it is, and asking her to be merciful in the reshuffling — that is the answer.</strong></p>
       <p>Oya is also the orisha of <em>sudden truth</em>. When something hidden is suddenly revealed — a secret kept for years, a betrayal exposed, a knowing that arrives uninvited at three in the morning — that is Oya's work. She tears the veil. She does not consult you about the timing. <em>She is fierce, and she is just, and she is on the side of truth, even when truth is uncomfortable.</em></p>`,

      `<h3>Working With Oya</h3>
       <p class="no-indent">Approach Oya when an ending is upon you and you need help <strong>letting it complete</strong>. When you have been holding onto a relationship, a job, a self-image, a city, an identity — and the holding has become the obstacle. The traditional Oya working is performed at the <em>edge of a cemetery</em> (without entering, unless you have specific business there) or at a <em>place where the wind is strong</em> — a hilltop, a beach in storm season, an open field.</p>
       <p>Bring nine eggplants (or nine purple plums), nine copper coins, a small length of nine-colored ribbon, and a piece of paper on which you have written the name of <em>what you are letting go</em>. (The relationship. The role. The story you have been telling about yourself.) Light a single dark-purple or maroon candle. Speak: <em>"Oya, mother of the storm, mistress of the threshold — I bring you what I cannot let go of by myself. Take it. Carry it where it needs to go. Make me ready for what is coming."</em></p>
       <p>Tear the paper into nine pieces. Burn them, one at a time, in the candle's flame, scattering the ash to the wind as you go. Leave the eggplants and coins at the site. Walk away without looking back. <strong>Within nine days, the thing will release its grip on you.</strong> Sometimes the release is dramatic — sudden and clear. Sometimes it is quiet — you simply notice, on the tenth morning, that you are no longer thinking about it. <em>Either way, the work is complete.</em></p>`,

      `<h3>The Right Storm at the Right Time</h3>
       <p class="no-indent">A teaching that needs to be said plainly: <strong>not every storm in your life is from Shango or Oya</strong>. Sometimes the storm is from your own poor choices, your unresolved trauma, the consequences of others' actions. The work is to <em>discern</em>. The Shango/Oya storm has a particular character: it arrives at the moment something <em>was supposed to end anyway</em>. It clears the ground for something new. Afterward, even though the experience was painful, you can see — with hindsight — that it was <em>necessary</em>.</p>
       <p>The non-divine storm has a different character. It is repetitive (the same kind of disaster again and again). It does not lead to growth. It leaves you flatter, not refined. <em>This is not Shango's lightning. This is unprocessed pattern.</em> For non-divine storms, the work is healing — therapy, ancestor work, ritual cleansing, sometimes a difficult conversation. For divine storms, the work is <em>cooperation</em>: recognizing that the lightning is on your side and getting out of its way.</p>
       <p>How do you tell which is which? Pour libation. Sit at the altar. Ask the ancestors. <strong>The well-tended ancestor knows the difference between the storm that is being sent for your good and the storm that is being made by your unhealed self.</strong> They will tell you, if you ask.</p>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Sit with a single question, at the altar, for seven evenings: <em>"What in my life is currently being torn down — and is it being torn down by me, or for me?"</em> Do not answer quickly. Let the question stay open. Light a single red or maroon candle for the asking.</p>
       <p>If by the seventh evening the answer is <em>"by me"</em> (you are doing damage from unprocessed pattern) — go back to the ancestor altar. Begin the elevation work for whichever ancestor's grief is moving through you. This is not a Shango/Oya situation. This is a healing situation.</p>
       <p>If the answer is <em>"for me"</em> (the storm is doing necessary work) — light one red candle for Shango on a Wednesday or Friday and one purple candle for Oya on a Wednesday. Speak briefly to each: <em>"I see you. I am not fighting the wind. Make the transformation as merciful as possible. Make me ready for what comes after."</em> Then trust the storm.</p>
       <p class="no-indent" style="margin-top:24px;text-align:center;font-style:italic;color:#5a3a14;">Next chapter: <em>The Body as Living Temple</em> — how the orisha live <em>inside</em> you, mapped to the chakras, and how to find your head orisha.</p>`
    ]
  },

  // ─── LESSON 5 — The Body as Living Temple ────────────────────
  { id:'o5', name:'The Body as Living Temple', time:'22 min',
    glyph:'☥', x:'70%', y:'78%',
    prompt:'Which orisha lives loudest in your body? Which one are you starving?',
    lead:'The orisha are not only out there. Each one has an address inside you — and your body is the building.',
    excerpt:'The deepest teaching of this module: <strong>the orisha dwell within human existence</strong>. They are mapped to the body\'s major energy centers. Building character means cleaning the rooms where they live. Today we meet the <em>Orisha-Chakra map</em>, and we begin the work of finding your <strong>Olori</strong> — the orisha who rules your head.',
    pages: [
      `<p class="dropcap no-indent">If you have followed the module attentively, you have noticed something: every Orisha we have met has had a <strong>color, a number, a day, an offering, a domain</strong>. The system is precise. It is also not just a list of external deities to be petitioned. The deepest teaching of the African spiritual house — the one that elevates this from polytheism to a <em>living psychology</em> — is that <strong>the Orisha dwell within human existence</strong>. They are not only out there in their domains; they are <em>in here</em>, in the body, mapped to specific addresses you can locate.</p>
       <p>This is what the elders mean when they say <em>iwa-pele is the goal of orisha relationship</em>. The point is not to win favor from external gods. The point is to <strong>build balanced character by cleaning the internal rooms where each orisha lives</strong>. The seven major orisha map to the seven major energy centers of the body — what other traditions call chakras, what the Yoruba call by their own names, but the cartography overlaps in remarkable ways. <em>Your body is a living temple, and each orisha has a room.</em></p>
       <div class="bk-quote">"Your body is a living temple. Each orisha has a room. The work is keeping the rooms clean."</div>`,

      `<h3>The Map — Bottom to Top</h3>
       <p class="no-indent">The traditional Orisha-chakra correspondence used in this curriculum runs as follows:</p>
       <p><strong>Root (base of spine) — Shango.</strong> Foundation, justice, the wise application of force, courage. When this center is weak, you cannot stand your ground; when it is calibrated, your "no" carries weight.</p>
       <p><strong>Sacral / Reproductive (lower belly) — Yemoja.</strong> Family, ancestry, the ocean of inherited memory, fertility (literal and creative). When this center is weak, you cannot feel held by your lineage; when it is calibrated, you carry the womb of the world inside you.</p>
       <p><strong>Solar plexus / Navel — Oshun.</strong> Sweetness, self-worth, love, art, money. When this center is weak, you cannot believe you are worth being loved; when it is calibrated, you receive what you offer.</p>
       <p><strong>Heart — Ogun.</strong> Inner strength, the balance between armor and tenderness, the courage to keep building. When this center is weak, you cannot face conflict without collapsing; when it is calibrated, your heart is a workshop where the path is forged daily.</p>
       <p><strong>Throat — Obatala.</strong> Speech, ethical clarity, the cool head, the word that does not wound unnecessarily. When this center is weak, you say what you do not mean; when it is calibrated, your speech is white-cloth clean.</p>
       <p><strong>Third eye (between brows) — Orunmila.</strong> Wisdom, divination, cosmic law, the seeing-beneath-the-surface. (We meet Orunmila in earnest in Module IV; he sits at this gate.) When this center is weak, you cannot read the script of the world; when it is calibrated, the world becomes legible.</p>
       <p><strong>Crown (top of head) — Ori, with Olódùmarè above.</strong> Your direct line to Source. Your destiny self. The crown you were born wearing. (Ori, you remember, was the entire subject of Module I, lesson 3.)</p>`,

      `<h3>Eshu and Oya — Where Do They Live?</h3>
       <p class="no-indent">A question careful students always ask: <em>where are Eshu and Oya in the map?</em> They are not in the seven main centers. The traditional teaching places them as <strong>guardians of the boundaries between</strong> the centers — Eshu at every threshold, every transition between one chakra and the next, and Oya at the boundaries that need to be <em>broken</em> for energy to move when stuck.</p>
       <p>Practically, this means: when energy is blocked between, say, the heart and the throat (you feel something but cannot speak it), Eshu is the orisha you call to <em>open the channel</em>. When energy is stuck because an old structure is keeping it stuck (a defended heart, a constricted throat, a locked womb), Oya is the orisha you call to <em>tear the structure down</em>. Eshu and Oya are not <em>in</em> the centers; they are the <em>passageways and the dynamiters</em>. They make the rest of the system work.</p>`,

      `<h3>Reading Your Own Body</h3>
       <p class="no-indent">A practical exercise the elders use to help students find their internal orisha-map. Sit quietly. Move your attention slowly from the base of your spine to the crown of your head, pausing at each of the seven centers. At each one, ask: <em>"Is this room clean? Is this room loud? Is this room starved?"</em></p>
       <p>You will notice patterns. One or two centers will feel <strong>loud</strong> — overactive, dominant, the orisha there running everything. One or two will feel <strong>starved</strong> — dim, weak, the orisha there neglected. The loud rooms are not bad; they are simply <em>where you have been living</em>. The starved rooms are not bad either; they are <em>where you have been afraid to live</em>.</p>
       <p>For example: if your throat (Obatala) is loud and your sacral (Yemoja) is starved, you may be a person who can speak with great clarity but cannot feel held by your family or lineage. The work is not to silence Obatala. The work is to <em>feed Yemoja</em>. Bring blue cloth, salted water, the holding the body has been missing. Over weeks, the imbalance recalibrates.</p>
       <p>If your root (Shango) is starved and your solar plexus (Oshun) is loud, you may be a person who knows how to be sweet, how to charm, how to receive — but who collapses when it is time to stand your ground. The work is not to suppress Oshun. The work is to <em>feed Shango</em>. Red apples. The double axe on the altar. The willingness to take up space.</p>
       <div class="bk-quote">"The loud rooms are where you have been living. The starved rooms are where you have been afraid to live."</div>`,

      `<h3>Finding Your Olori — The Head Orisha</h3>
       <p class="no-indent">In traditional Ifa houses, every initiated person has an <strong>Olori</strong> — the orisha who "rules the head." This is determined formally through divination, by an Ifa priest, in a ceremony that takes hours and involves sacred palm nuts, the divining chain, and the careful reading of the Odu (we will meet all of this in Module IV). The Olori is, broadly, the orisha whose character runs most strongly through your own — the dominant note in your spiritual chord.</p>
       <p>For a student who is not yet initiated, the formal Olori cannot be determined definitively. But you can <strong>begin to feel</strong> who it is likely to be. The Olori is usually the orisha whose room is <em>loudest and most luminous</em> in your body, the one whose myths feel uncannily familiar when you read them, the one whose color you find yourself wearing without thinking, the one who shows up most often in your dreams. <em>You cannot pick your Olori. Your Olori picks you.</em> The work, before initiation, is simply to <strong>notice who keeps showing up</strong>.</p>
       <p>A note of caution: many students, drawn to the more dramatic Orisha (Oya, Shango), declare those orisha their Olori within their first month of practice. The elders are gentle but clear: <em>your Olori is rarely who you would have chosen</em>. The orisha who actually rules your head is often the one you most overlooked, took for granted, or did not at first find glamorous. <strong>Pay attention to the quiet ones. Pay attention to the orisha you keep dismissing.</strong></p>`,

      `<h3>The Seven-Day Body Scan</h3>
       <p class="no-indent">A practice used in many traditional African and diaspora houses: for seven consecutive evenings, before sleep, do a slow body scan from root to crown, naming the orisha at each center. <em>"Shango at the root. Yemoja at the womb. Oshun at the navel. Ogun at the heart. Obatala at the throat. Orunmila at the brow. Ori at the crown."</em> At each name, place your hand briefly over the corresponding part of the body, and breathe.</p>
       <p>By the third or fourth night, you will start to feel which centers respond and which do not. By the seventh, a clear picture will emerge of where your internal temple is well-tended and where it has been neglected. <strong>This is more useful than any external diagnostic. You are reading your own architecture.</strong></p>
       <p>Once you know where the work is, you can target your offerings. A starved Shango wants red apples and the willingness to stand up. A starved Yemoja wants blue cloth and time near deep water. A starved Oshun wants honey and the willingness to receive a compliment without deflecting. A starved Ogun wants iron implements and physical labor that uses your hands. A starved Obatala wants white cloth, silence, and a moratorium on cruel speech. A starved Orunmila wants stillness, study, and the willingness to slow down enough to read the signs. A starved Ori wants <em>asking</em>: a daily petition to your own crown for guidance, with the recognition that no god blesses without Ori's consent.</p>`,

      `<h3>Iwa-Pẹlẹ — The Goal Restated</h3>
       <p class="no-indent">We end where Module II ended, but at a deeper layer: <strong>the goal of orisha relationship is not magical power, social standing, or escape from suffering — it is the building of Iwa-pẹlẹ, balanced character</strong>. Each orisha you tend is, in effect, a <em>training program</em> for a specific virtue. Shango trains righteous force. Obatala trains ethical restraint. Oshun trains generous reception. Yemoja trains the ability to be held and to hold. Ogun trains the courage of daily building. Oya trains the willingness to let things end. Eshu trains the awareness of how every doorway costs something to pass through.</p>
       <p>A person who has tended all seven for years walks differently. They are not a saint — the tradition is not interested in sainthood. They are <em>balanced</em>. When a difficult moment arrives, they have all seven rooms to draw from. They can be sweet with Oshun and fierce with Shango in the same hour. They can hold with Yemoja and let go with Oya in the same week. <strong>This is the actual goal: not to become any one orisha, but to become a person in whom all seven can live without war.</strong></p>
       <div class="bk-quote">"The goal is not to become any one orisha — but to become a person in whom all seven can live without war."</div>`,

      `<h3>Your Practice This Week</h3>
       <p class="no-indent">Two practices, layered:</p>
       <p><strong>Daily — the seven-day body scan.</strong> Each evening, before sleep, scan from root to crown, naming the orisha at each center, breathing into the room. Note in your journal: which rooms felt loud? Which felt starved?</p>
       <p><strong>Once during the week — feed your most starved center.</strong> Whichever orisha came up as the most under-tended, make one small dedicated offering at your altar this week. The offering matches the orisha (red apple for Shango; honey for Oshun; salted water for Yemoja; iron implement for Ogun; white candle for Obatala; a few minutes of silent study for Orunmila; one petition to your own Ori for clarity). Speak the orisha's name. Sit for three minutes. Notice what shifts, in your body, in the days that follow.</p>
       <p>By next week, your internal temple will be one room cleaner than it was. This is how the work proceeds — not in dramatic conversions, but in <strong>one room at a time, over years</strong>.</p>
       <p class="no-indent" style="margin-top:32px;text-align:center;font-style:italic;color:#5a3a14;">Module III complete. Next: <em>Divination — Listening to the Bones</em>, where we meet Orunmila in earnest and learn to read the script of the world through Ifa.</p>`
    ]
  }

];
